### ISSUE TITLE
Support External transaction Manager that does not use ThreadLocal

### ISSUE THREAD

**Issue by benmccann** [ebean-orm/ebean#1009]
It would be nice for the transaction store to be pluggable so that users can provide alternate implementations in lieu of DefaultTransactionThreadLocal. ThreadLocal does not play well with asynchronous programming because different threads are executing different futures and Play Framework heavily encourages asynchronous programming.

**Comment by rbygrave** [comment]
This already partially exists per say as io.ebean.config.ExternalTransactionManager

Currently it has 2 implementations being Spring and JTA.

Internally both of these implementations make use of DefaultTransactionThreadLocal to propagate transactions from the external transaction manager 'scope' into Ebean's transaction scope.

As I see it Play Framework would have a "context" that performs a similar role to ThreadLocal.  It would be a matter of knowing what that was ... and using that instead of DefaultTransactionThreadLocal - in addition to the ExternalTransactionManager. 

Does that make sense?  How is the "context" propagated in Play?

**Comment by rbygrave** [comment]
I'm not going to action this myself.  Happy for someone else to support the desired information regarding alternate ThreadLocal (in Play particularly).  At that point we can re-open and go from there.

Closing for now until we get the information to pursue further.
