### ISSUE TITLE
Create valid migration scripts for non-Postgres databases and @DbArray columns.

### ISSUE THREAD

**Issue by focbenz** [ebean-orm/ebean#1011]
According to the documentation for non-Postgres databases the @DbArray annotation will just store the data in VARCHAR columns with JSON content. Adding a new @DbArray annotated column to an existing table causes an issue with a sqlserver database.

## Expected behavior
Only use the SQL array notation varchar[] for Postgres and normal varchar or varchar(length) types for non-Postgres databases migration ddl scripts.

## Actual behavior
Also for non-Postgres databases the varchar[] notation is used.

### Steps to reproduce

```java
@DbArray
private String dbarray_added_to_foo;
```

ddl script sqlserver **FAIL**
```
alter table foo add dbarray_added_to_foo varchar[];
```

ddl script sqlserver **(expected)**
```
alter table foo add dbarray_added_to_foo varchar;
```

ddl script postgres **OK**
```
alter table foo add column dbarray_added_to_foo varchar[];
```

I have created a Pull Request with a JUnit test that should demonstrate the issue:
https://github.com/ebean-orm/ebean/pull/1010

**Comment by focbenz** [comment]
Example with length specified in @DbArray annotation:

```java
@DbArray(length = 66)
private String dbarray_with_length_added_to_foo;
```

ddl script sqlserver **FAIL**
```
alter table foo add dbarray_with_length_added_to_foo varchar[];
```

ddl script sqlserver **(expected)**
```
alter table foo add dbarray_with_length_added_to_foo varchar(66);
```

ddl script postgres **OK**
```
alter table foo add column dbarray_added_to_foo varchar[];
```

**Comment by rbygrave** [comment]
So with this fix note that the "logical DB type" which is in the migration xml will be something like:

- varchar[](66) ... when a length of 66 is defined for the failover when the db does not support ARRAY
- varchar[] ... when no length is defined (so defaults to varchar(1000) in the fallback case)
- integer[](66) ... when the element type is an integer rather than string
- integer[]

These "logical DB types" get converted into platform specific types. For H2 these all become ARRAY.  For Postgres we remove the fallback (66) part if defined. For other DB's like SQL Server, MySQL etc these become varchar(66) etc with the fallback of varchar(1000).

### Example migration xml
```xml
<addColumn tableName="contact">
    <column name="tags" type="varchar[](90)" notnull="true"/>
    <column name="scores" type="integer[]" notnull="true"/>
</addColumn>
```
