### ISSUE TITLE
PlatformPrefix isn't actually used

### ISSUE THREAD

**Issue by KoenDG** [ebean-orm/ebean#1058]
This field here: https://github.com/ebean-orm/ebean/blob/master/src/main/java/io/ebean/dbmigration/model/PlatformDdlWriter.java#L32

Never actually used anywhere in the project. What is its intended purpose? To prepend something to the ddl or more related to a filename?

**Comment by rbygrave** [comment]
You are correct in that it can be removed from that location (so I'll do that).

> What is its intended purpose?

We can have our 'logical database migration' generate DDL for more than one platform at a time.  For example we can generate DDL for both Postgres and MySql with the code below:

```java
          DbMigration migration = new DbMigration();
          migration.setPathToResources("src/main/resources");
   
          migration.addPlatform(DbPlatformName.POSTGRES, "pg");
          migration.addPlatform(DbPlatformName.MYSQL, "mysql");
   
          migration.generateMigration();
```
So that `prefix` is the `pg` and `mysql` values with puts the DDL into subdirectories.

**Comment by rbygrave** [comment]
Removed, closing.
