### ISSUE TITLE
L2 query cache not caching empty result set

### ISSUE THREAD

**Issue by kpysniak** [ebean-orm/ebean#1217]
I recently started using ebean orm cache for L2 caching SQL database. All works fine, but one of the problems I have encountered is that when a query is executed and an empty result set is returned, that DB response is not cached.

My question is whether it is done on purpose or whether it is a missing functionality in ORM Cache?

Thanks for help!

**Comment by rbygrave** [comment]
So DefaultOrmQueryEngine line 165 has:

```java
if (!result.isEmpty() && query.getUseQueryCache().isPut()) {
```
So we are only putting into the query cache non-empty results ... and the question is - Is this expected behaviour or a bug.

Or said another way, is there any reason why Ebean isn't caching an empty result with the query cache.
---

No, this is really a bug.  We should cache an empty result in the query cache.

**Comment by kpysniak** [comment]
@rbygrave thanks for a quick solution, when could we the update to be released?

**Comment by kpysniak** [comment]
@rbygrave Are you sure it works? I'm not sure if the implementation works with ConcurrentHashMaps
