### ISSUE TITLE
Support use of application.yml and application-test.yml ... (as alternative to ebean.properties, test-ebean.properties)

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1246]
So this ticket is open for feedback and comments but the gist is:

- application.yml ... is a pretty common (almost expectation) for configuring applications these days (at least that is my impression)
- It is good to have configuration in one place (rather than separate ebean specific config files, docker-run.properties etc ... it is better this is all together with the rest of the configuration)
- This should make things even easier for SpringBoot + Ebean users

## General plan

Ebean will:
- read src/main/resources/application.yml
- read (and override with) src/test/resources/application-test.yml  (if exists so only in test)
- read (and override with) command line defined application yml

We note of course that `application-test.yml` won't exist in a deployed application (so won't exist, won't be read).

We will evaluate expressions such as `${db_user:someDefault}`
- where we look for `db_user` as environment variable and system property (as we do now with ebean.properties)
- we use the value past the colon (e.g. `someDefault`) as the default value for the property

---
So happy to hear feedback on this but I'll probably be looking at this very soon.

**Comment by dastultz** [comment]
We have a couple Spring Boot apps, so I like this idea. We use `application.properties` rather than `yaml`, for no particular reason, I just want make sure what we're doing is not at odds with this idea.

We have a multi-tenant app, old school 7.x. We read properties from `application.properties` with placeholders such as:

`datasource.__TENANT_ID__.username=foo`

We iterate over the properties for each tenant to instantiate an `EbeanServer` for and substitute the tenant ID.

We're working on upgrading to the latest Ebean and following that soon with adopting Ebean's multi-tenant support. If there's a better way with that feature than what we are doing great. If not, the new idea here should not conflict with what we are doing. I guess that's not likely since we are using the properties file rather than yaml.

**Comment by rbygrave** [comment]
Yes I don't see a problem / conflict with what you are doing.

We will confirm when we get something more concrete but I don't see an
issue.

Cheers, Rob.

**Comment by rbygrave** [comment]
So the load logic is:

## Main configuration
Load from resources:
- application.properties
- application.yml
- ebean.properties

Load from files:
- application.properties
- application.yml
- ebean.properties

Then loads from environment variable <em>EBEAN_PROPS_FILE</em>
Then loads from system property <em>ebean.props.file</em>
Then loads from <em>load.properties</em>

## Test configuration

Once the main configuration is read it will try to read common test configuration. This will only be successful if the test resources are available (i.e. running tests).

Loads from test resources
- application-test.properties
- application-test.yml
- test-ebean.properties


This means that ServerConfig.loadTestProperties() is no a no-op ... and is deprecated.

PropertiesWrapper also loses it's withPrefix() and asPropertiesLowerCase() methods.

**Comment by soberich** [comment]
Alright, I see https://github.com/ebean-orm/ebean/issues/1555

**Comment by rbygrave** [comment]
Thanks @soberich  ... I forgot to mention that here.  Good to link the issues etc.
