### ISSUE TITLE
ENH: Add ServerConfig notifyL2CacheInForeground option ... was ServerCachePlugin BackgroundExecutor problem

### ISSUE THREAD

**Issue by Ryszard-Trojnacki** [ebean-orm/ebean#1258]
I have such a test case:
```java
	@Test
	public void testUserAdditionalData() {
		User user = userDA.createTestUser(RandomStringUtils.randomAlphanumeric(5));
		
		userDA.setUserAdditionalData(user, "pure_test", 2);
		userDA.setUserAdditionalData(user, "pure_test", 3);
		user = userDA.getById(user.getId());

		log.d("Additional data: %s", user.getData());
		long number = userDA.getUserAdditionalData(user, "pure_test");
		assertEquals(3, number);		
	}
```
This test creates enitity User (db.insert), then sets a field (JSON field) with update (db.update) and this is sometimes (number is 2, 3 or null) not working when ServerCachePlugin is enabled (Apache Ignite).
From my analysis it looks that TransactionManager.java:
```java
  public void notifyOfCommit(SpiTransaction transaction) {
     ...
      postCommit.notifyLocalCache();
      backgroundExecutor.execute(postCommit.backgroundNotify());
     ...
  }
```
Is doing this (updating cache) in background thread, therefor db.find() is not getting the actual version of this object.
Shouldn't this be done in foreground thread or shouldn't there be atleast options to set this to work in foreground.

When ServerCachePlugin is not enabled and default l2cache is working, then this is done in foreground... which is logic and works like expected.
```java
 void notifyLocalCache() {
    processTableEvents(event.getEventTables());
    if (manager.localL2Caching) {
      // process l2 cache changes in foreground
      processCacheChanges(event.buildCacheChanges(manager.viewInvalidation));
    } else {
      // collect l2 cache changes for delayed background processing
      cacheChanges = event.buildCacheChanges(manager.viewInvalidation);
    }
  }
```

**Comment by rbygrave** [comment]
> Shouldn't this be done in foreground 

In general no in that ... performing the notifications to a distributed cache makes network calls. We don't know how big the transaction is in terms of how many types are changed etc so generally we want to do that all in the background.

Doing it in the background is (to date) only been problematic from a testing perspective. That is, there are not many (any so far) use cases where at the end of the transaction ... code wants to fetch back what it has been processing (we only do this sort of thing in tests thus far).

>  default l2cache is working,

Yes ... via that `manager.localL2Caching` (because we know it is cheap call)

>  shouldn't there be at least options to set this to work in foreground.

So I would say yes but we do need to think about "why" and hence the "use cases" we are supporting.  That is, perhaps we want to do this for testing purposes when we are testing against a non-local cache like Ignite or Hazelcast (as opposed to on a per transaction basis etc).

For testing purposes somewhat implies a global flag (on ServerConfig) ... so when we are running tests we configure: 
```java
serverConfig.setNotifyL2CacheInForeground(true)
```

So a serverConfig `notifyL2CacheInForground` ... should effectively replace that `manager.localL2Caching` really.

**Comment by Ryszard-Trojnacki** [comment]
I have a use case in which such a problem make occur.

In my application I have a web form system, that works in plugings manner. 
That is - a form fragment is not aware of other form fragments because it depends of enabled plugins. When user wants to save form, then every plugin does changes and saves data to data base. In this scenario is normal thing is that few of form fragments load the same bean (db.find) do changes in it (db.update). All of this is done in one http request processing code.

> So a serverConfig notifyL2CacheInForground ... should effectively replace that manager.localL2Caching really.
Yes that would be very helpful. So far I just changed the code of TransactionManager.notifyOfCommit that this is done in foreground, but it will exclude me from updates...

**Comment by rbygrave** [comment]
So with this fix / change we can set notifyL2CacheInForeground to true ... on serverConfig.

```java
serverConfig.setNotifyL2CacheInForeground(true)
```
or ...
```properties
ebean.notifyL2CacheInForeground=true
```
... and we note that we still do not yet need this on a per transaction basis - we don't yet need to override / control this for specific transactions.  We are not adding transaction.setNotifyL2CacheInForeground(boolean) ... at this stage unless people hit that use case.
