### ISSUE TITLE
[Cancelled] Change behavior of delete on a bean with ManyToMany such that it maintains the intersection table without needing CascadeType.REMOVE

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1266]
I kind of need this change reviewed ... and I think Daryl is my man to do that.

**Background:**
I have put in support for `OneToMany` with `JoinTable` which operates in basically the same was as `ManyToMany` and in doing so found the current behaviour of delete() on a bean with `ManyToMany` somewhat inconsistent.  That is, I don't think we do the best/simplest thing.

The JPA spec says `CascadeType.REMOVE` on a `ToMany` is not portable. That is, the spec does not define the behaviour of what the JPA provider should provide for these 2 cases:

- Deleting a bean that has a `ManyToMany` with / without CascadeType.REMOVE
- Deleting a bean that has a `OneToMany` with a `JoinTable` with / without CascadeType.REMOVE

With both of these cases there is a `intersection` table that is automatically maintained by the ORM (and this table is not explicit in the ORM model so it must be maintained). 

Currently our behaviour when you delete a bean with a `ManyToMany` that DOES NOT have a CascadeType.REMOVE matches Hibernate. This means it doesn't automatically delete the associated rows from the intersection table. 

This means as developers we instead need to effectively fetch all the entries in the collection, clear them and then do the delete - I believe this is a bit of pain for developers that we could avoid and instead we should just delete the associated rows from the intersection without any CascadeType.REMOVE defined.

## Example:

A User has many roles.

```java
// we can't just delete the user if they have roles ... we get a constraint violation
Ebean.delete(user);
```
Ultimately the question is whether it is useful behaviour to fail the delete in this case.

## Map with CacadeType.REMOVE

Now in Ebean if we map a ManyToMany with CacadeType.REMOVE we do NOT go over to the other side and delete the beans themselves - we only ever maintain the intersection table (so this is what we are asking people to do).

However, Hibernate with CascadeType.REMOVE will go over and for example delete the actual Roles that were linked to the User. This means the "internet" is full of advice about not having CacadeType.REMOVE on a ManyToMany.

## Clear roles first

Currently without CascadeType.REMOVE we are asking developers to fetch and clear the roles first before we delete the user:
```java
// clear the roles first  
user.getValidRoles().clear();
Ebean.save(user);

// ok, now we can delete the user
Ebean.delete(user);
```
This is a fairly inefficient approach compared to Ebean automatically maintaining it via a single bulk update statement.

## Summary

I think for a delete we should automatically maintain the intersection table on a ManyToMany regardless of a CascadeType.REMOVE.

The only thing we lose in doing this is that if people want to check for references prior to a delete they need to fetch those first and check it is empty.  At the moment they could just catch the constraint violation - this seems like it would be a pretty rare case to me (and instead we have made the very common case much harder than it should be).

--- 
Is there anyone using `ManyToMany` without `CascadeType.REMOVE` ... that likes and wants the current behaviour (that the intersection is not maintained on delete)?

Thanks, Rob.

**Comment by dastultz** [comment]
I have 60+ `@ManyToMany` mappings. The vast majority are `CascadeType.PERSIST`. I suspect the few that do not have `CascadeType.PERSIST` are meant to. I'm guessing I found that the collection _changes_ would not be saved when the parent is saved without `CascadeType.PERSIST`. I don't see this pattern in the older JPA mappings I still have.

I have zero `CascadeType.REMOVE` annotations in my project (and just 2 special-case `CascadeType.ALL` on `@OneToMany`.

My project was started many years before adopting an ORM (or two). Probably just about all of our many-to-many join tables are defined as cascade delete in the database. I don't know if I ever experimented with `CascadeType.REMOVE` with Ebean mapping, I do recall JPA deleting the entire related join table records and reinserting for a simple remove or add of one or two records, I feel like deletes were similar, load and iterate over the children and delete one by one. Ick.

So since we already were in the habit of defining join tables as cascade delete and I didn't like the way OpenJPA did deletes (and maybe Ebean at the time, I don't recall, don't take offense if I'm mistaken) we are happy to not use `CascadeType.REMOVE` and get the more efficient cascade delete. So we never "manually" manage the delete of the children with Ebean ("Clear Roles First").

> Now in Ebean if we map a `@ManyToMany` with `CacadeType.REMOVE` we do NOT go over to the other side and delete the beans themselves

Oh, yeah, Ebean definitely does the right thing here. Not sure if I was involved in any change in behavior in Ebean wrt this, but it should behave like a database with cascade delete - the database doesn't delete the "other side".

The goal of this issue is to make `CacadeType.REMOVE` on `@ManyToMany` essential functionless - it has no effect. So if your database does not do cascade delete and you do not have `CacadeType.REMOVE`... you still effectively get `CacadeType.REMOVE`.  As you say, the developer can first check if there are any children and block the delete if desired. I have never had a need for this behavior, but it does not seem intuitive, meaning it's not obvious and people might struggle with it.

The important question, how will this affect ME? :-) My `@ManyToMany`'s do not have `CacadeType.REMOVE` but I do have cascade delete defined in the DB. This means Ebean will be doing an unnecessary delete. If this is efficient (not loading and iterating children) like with a simple subquery, then this will probably have no obvious impact.

I suppose I'd have to go through all of my join table definitions and make sure all are cascade delete.

**Comment by rbygrave** [comment]
Thanks Daryl - 60+ ManyToMany mappings - wow!!.  Well, I think we should mull this over some more.  

It seems to me that we could just document it clearly that `Cascade.REMOVE` on a `@ManyToMany` for Ebean means we delete from intersection table only (unlike hibernate in particular) and then we can have both behaviours without any extra annotations which is good.

In other words, leave it as is, enabling us to have both behaviours and just documenting it explicitly.

**Comment by rbygrave** [comment]
So yes, in the absence of any other comments we will `leave the behavior as is` and close this.

No change.
