### ISSUE TITLE
Change MigrationXmlWriter to not write <!DOCTYPE xml> (as it is not needed/expected now)

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1384]

**Comment by focbenz** [comment]
Hi @rbygrave,

Would you instead reference a DTD or XML schema?
I initially added the DOCTYPE xml to get rid of the warning that the Eclipse IDE shows for all XML files without DTD or XML schema.

**Comment by rbygrave** [comment]
It has the xmlns -  `<migration xmlns="http://ebean-orm.github.io/xml/ns/dbmigration">`  so what are you suggesting?  

The DOCTYPE xml is considered invalid by IntelliJ IDEA.

**Comment by focbenz** [comment]
Yes the namespace is correctly referenced but the URL just produces a 404 error.
I am not 100% sure how the validation in Eclipse works ... but declaring the "empty" DTD with `<!DOCTYPE xml>` before did not generate a warning because that line just states there is no DTD.

If XML schemas should be used some schemaLocation is missing, so that the xml files can be validated. Although I tried to create a working sample with the latest ebean-dbmigration.xsd (https://raw.githubusercontent.com/ebean-orm/ebean/ded7d44974c33c9cdee5be2aaf993e7a4620237d/src/main/resources/ebean-dbmigration-1.0.xsd) that I found I failed miserably. Maybe you are more of an XML master than me ;-) 

Having the correct XSD file linked should disable warnings / errors in both IDEs (Eclipse and IntelliJ IDEA)
