### ISSUE TITLE
FOR UPDATE queries inside a transaction are not honored when beans are already cached (in the persistence context)

### ISSUE THREAD

**Issue by wesleysee** [ebean-orm/ebean#1401]
## Expected behavior
I expect the FOR UPDATE queries to still be executed even if the bean is already in the [persistence context] L1 cache.

This seems similar to https://github.com/ebean-orm/ebean/issues/970

## Actual behavior
FOR UPDATE query is not executed if inside a transaction and bean is already in the  [persistence context] L1 cache

### Steps to reproduce

```java
Transaction transaction = Entity.db().beginTransaction();
Entity.find.byId(entityId);
// never executed
Entity.find.query().setId(entityId).forUpdate().findOne();
transaction.end();
```

```console
// only one query according to the logs
DEBUG io.ebean.SQL - txn[1007] select t0.id from entity t0 where t0.id = ?  ; --bind(1, )
```

**Comment by xunnanxu** [comment]
I think the expected behavior should be `FOR UPDATE` should be executed, unless there's already one executed before this statement in the same transaction.

**Comment by xunnanxu** [comment]
@rbygrave  Right now the workaround is to use `.setPersistenceContextScope(PersistenceContextScope.QUERY)`  for that statement.

**Comment by rbygrave** [comment]
Yes I am happy the the behaviour that you expect to see (that the select for update is executed) is correct.

I have just pushed a fix for this issue.  Note that the fix means that the `select for update` is executed but note that the persistence context is still used when reading/building the object graph.

That means, with this fix `the same bean instance is returned` ... but yes the select for update statement is executed (so we have the database lock which is what we want and expect).

The workaround of using `.setPersistenceContextScope(PersistenceContextScope.QUERY)` is still a valid and correct option even with this fix.  What that means is that with using `PersistenceContextScope.QUERY` the bean returned by the second query is a different instance.  For some use cases this is still going to be the more correct / expected behaviour and we should use this explicitly when we want to ensure we get a fresh version of the bean returned.
