### ISSUE TITLE
Ebean Postgres DDL maps BigDecimal to decimal with scale 0

### ISSUE THREAD

**Issue by maherm** [ebean-orm/ebean#1458]
PostgresPlatform maps BigDecimal to "decimal(38)", which means precision 38 and scale 0.
That means all BigDecimal values are rounded to the next integer.

## Expected behavior
It should be possible to store BigDecimal values with Ebean and Postgres.

## Actual behavior
All BigDecimal values are rounded to the next integer.

### Steps to reproduce

```java
public class Thing {
	@Id
	public int id;
	public BigDecimal aNumber;
        //... getters and setters
}
```

```java
public class BigDecimalTest {
	@Test
	public void test() {
		BigDecimal number = BigDecimal.valueOf(12.34);
		Thing thing = new Thing();
		thing.setANumber(number);
		Ebean.save(thing);
		Ebean.refresh(thing);
		assertEquals(number, thing.getANumber());
	}
}
```

```console
java.lang.AssertionError: expected:<12.34> but was:<12>
```

**Comment by rbygrave** [comment]
The expectation is that for BigDecimal we specify scale and precision via `@Column`

For example:
```java
    @Column(precision = 10, scale = 3)
    private BigDecimal aNumber;
```

> PostgresPlatform maps BigDecimal to "decimal(38)"

That is correct. 

The question in terms of `is this a bug?` is whether or not this conforms to the JPA specification.  As understood this conforms to the JPA specification - that is, this is the expected mapping when we don't specify scale or precision.

## Summary
This is not considered a bug but the expected behaviour as per JPA spec.

The general note is that we should specify both `precision` and `scale` via `@Column` when mapping properties of BigDecimal type.

**Comment by maherm** [comment]
> This is not considered a bug but the expected behaviour as per JPA spec.

Wow, I missed that. Although I understand the reasoning behind it, it feels just like bad design to assume 0 would be a good default scale for decimal values. 
Even worse when you see that they don't even get it right themselves.  In all examples in the JPA spec that use BigDecimal, the ```@Column``` annotation is omitted, except the oneliner example for setting precision and scale... Thanks for the clarification.

**Comment by rbygrave** [comment]
Yes quite.  I'll close this.

Also note that for Ebean we can set/override the default type mapping (per platform or for all platforms). For example:
```java
// set the default mapping for BigDecimal.class/decimal
serverConfig.addCustomMapping(DbType.DECIMAL, "decimal(18,6)");

// set the default mapping for String.class/varchar but only for Postgres
serverConfig.addCustomMapping(DbType.VARCHAR, "text", Platform.POSTGRES);
```
