### ISSUE TITLE
A question about password

### ISSUE THREAD

**Issue by codem4ster** [ebean-orm/ebean#1518]
There is something like `${db.password:fred}` in password in application.yml generated by init script.
How can I use this (I cannot find in documentation) not to send my password to the repo.

**Comment by rbygrave** [comment]
Hi @codem4ster , just so that you know the intention for this project is to only use github issues for bugs, enhancements and refactoring code changes.

Questions should really be posted to https://groups.google.com/forum/#!forum/ebean

We document why we do this at: https://ebean-orm.github.io/support

Cheers, Rob.

**Comment by rbygrave** [comment]
Hi @codem4ster  ... not keen to post your question to the google group?  I'll tidy this up and close this.
