### ISSUE TITLE
Memory leak when using @Cache(enableQueryCache=true)

### ISSUE THREAD

**Issue by rPraml** [ebean-orm/ebean#1519]
I have a larger batch insert in my application, that runs with 1G max heap space and throws an OOM when I use the query cache

## Expected behavior
No OOM when using `@Cache(enableQueryCache=true)` in larger transactions. Using Query Cache should not increase the memory footprint too much.

## Actual behavior
When using the query cache, the Transaction stores all PersistRequestBean (and the bean with all its data) in the TransactionEventBeans, so that the GC cannot collect them. 

## Suggested fix
in most cases, it is not neccessary to store each bean. At the end of the transaction, the code will call BeanDescriptorCacheHelp.persistInsert, which will effectively call
```java
      queryCacheClear(changeSet);
      cacheDeleteImported(false, insertRequest.getEntityBean(), changeSet);
      changeSet.addBeanInsert(desc.getBaseTable());
```
for each bean. but this is not neccessary, because `queryCacheClear` and `changeSet.addBeanInsert` need to be called only once per descriptor. Calling `cacheDeleteImported` is required only when there are 'propertiesOneImported'

It would be also OK as temporary workaround, if I can disable the caching during my batch import transactions and invalidate the caches after that myself.

### Steps to reproduce

```java
/**
 *
 * Test preparation:
 *
 * - Enable file based H2 in ebean.properties (line `datasource.h2.databaseUrl=jdbc:h2:file:~/tests`)
 * - disable logging of io.ebean.SUM/TXN/SQL in logback-test.xml
 * - remove existing database in ~/tests (do that before each run)
 * - run this class with `-Xmx1g` jvm argument
 * - an OOM in iteration ~45000 will occur (45k * 10k chars = 45k * 20k bytes = 900MB string space)
 *
 * remove the line `@Cache(enableQueryCache=true)` - and it will run forever (until 500k beans
 * are written. = 10G string space)
 */
public class MainMemoryLeak {

  @Cache(enableQueryCache=true)
  @Entity
  public static class ECachedBean {
    @Id
    private Long id;

    @Lob
    private String description;
  }

  public static void main(String[] args) {

    // create a string with 10k chars
    char[] c = new char[10_000];
    Arrays.fill(c, 'x');

    try (Transaction txn = Ebean.beginTransaction()) {
      for (int i = 0; i < 500000; i++) {

        if (i % 1000 == 0) {
          long mem = Runtime.getRuntime().freeMemory() / 1024 / 1024;
          if (mem > 1024) {
            throw new IllegalStateException("-Xmx1g JVM argument expected");
          }
          System.out.println("Iteration: " + i + " Free mem: " + mem + " MB");
        }

        ECachedBean a = new ECachedBean();
        a.description = new String(c);
        Ebean.save(a);
      }
      System.out.println("Success, no mem limit detected");
      txn.commit();
    }

  }
}

```

```console
Iteration: 40000 Free mem: 115 MB
Iteration: 41000 Free mem: 95 MB
Iteration: 42000 Free mem: 58 MB
Iteration: 43000 Free mem: 76 MB
Iteration: 44000 Free mem: 69 MB
Exception in thread "MVStore background writer nio:C:/Users/praml/tests.mv.db" java.lang.OutOfMemoryError: Capacity: 7077888
	at org.h2.mvstore.WriteBuffer.grow(WriteBuffer.java:322)
	at org.h2.mvstore.WriteBuffer.ensureCapacity(WriteBuffer.java:302)
	at org.h2.mvstore.WriteBuffer.put(WriteBuffer.java:164)
	at org.h2.mvstore.type.ObjectDataType$ObjectArrayType.write(ObjectDataType.java:1375)
	at org.h2.mvstore.type.ObjectDataType.write(ObjectDataType.java:128)
	at org.h2.mvstore.type.ObjectDataType.write(ObjectDataType.java:122)
	at org.h2.mvstore.Page.write(Page.java:744)
	at org.h2.mvstore.Page.writeUnsavedRecursive(Page.java:825)
	at org.h2.mvstore.Page.writeUnsavedRecursive(Page.java:831)
	at org.h2.mvstore.Page.writeUnsavedRecursive(Page.java:831)
	at org.h2.mvstore.Page.writeUnsavedRecursive(Page.java:831)
	at org.h2.mvstore.MVStore.storeNowTry(MVStore.java:1151)
	at org.h2.mvstore.MVStore.storeNow(MVStore.java:1050)
	at org.h2.mvstore.MVStore.commitAndSave(MVStore.java:1039)
	at org.h2.mvstore.MVStore.writeInBackground(MVStore.java:2489)
	at org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:2720)
Iteration: 45000 Free mem: 55 MB
```

**Comment by rbygrave** [comment]
Some notes on the issue and fix implementation.

- The current problem is we keep the PersistBeanRequest's until post commit.  Instead we want to convert these into the CacheChangeSet as early as possible (allowing the persist requests to GC)
- We can't just put the requests into the cache change set on postCommit due to element collection handling
- For L2 cache Element collection is part of the bean data (but the many part can persist after postExecute of the bean depending on the use of batch)
- In general we desire to have the cache notify message added for the bean and the beans 'many' properties together at the same time (takes out the difference between element collection vs other many in terms of L2 cache)
- We have PersistBeanRequest.postExecute() and PersistBeanRequest.complete() ... which occur after the bean has been persisted & after the many properties have been persist cascaded to.  These can occur in different order depending on use of batch 

Ultimately the fix for this puts the L2 cache changes into the CacheChangeSet as soon as it can. It waits for both the PersistBeanRequest.postExecute() and PersistBeanRequest.complete() to be called before it does so.

**Comment by rbygrave** [comment]
Thanks @rPraml ... good one to find and nice manual test there.  We have a fix for this now, I've added some comments into the PR to maybe help follow the changes that were made to resolve this.

Cheers, Rob.

Closing with fix from associated PR.
