### ISSUE TITLE
ENH: Support query.setBaseTable() ... to query against dynamic table (ala manual table partitioning)

### ISSUE THREAD

**Issue by cn-core** [ebean-orm/ebean#1566]
Enhancement, support specifying a specific base table (when there is logical table partitioning).

```java
query
  .setBaseTable("item_2019_01")
  .where()...
  .findList()
```

```sql
select ... from item_2019_01 ...
```

------------------
 How to map entity to dynamic table?
  For eg. I have one table named task, and other table named like items_taskId, the taskId is a dynamic value from table task.
  How can i map the Entity Item to the dynamic table?
  The simple thing want to do is change the final sql "from item" to "from item_xxx", has someone know?

**Comment by heqiqi** [comment]
As far, it seems ebean doesn't support dynamic mapping. could you try the rawsql instead?

**Comment by rbygrave** [comment]
From the google group answer:
-------
Ebean isn't able to do that in that there isn't a query.setBaseTable("item_xxx").

In terms of code:
SqlTreeNodeRoot line 68 has:
ctx.append(desc.getBaseTable(temporalMode));

... so that is what would need to change.

SqlTreeBuilder line 281 ... is where the query could put a "custom base table" into the SqlTreeNodeRoot
... and then need to take query plan key into account etc.

**Comment by rbygrave** [comment]
I'll re-open this and turn it into an enhancement request (for those people using databases without built in table partitioning).

To be clear though ... unless more people actually help with improving the documentation then this won't get addressed quickly.  Documentation and several other things need the attention and the lack of committers to https://github.com/ebean-orm/website-source is disappointing.

Cheers, Rob.
