### ISSUE TITLE
Q: `@PrimaryKeyJoinColumn` behaviour within transaction.

### ISSUE THREAD

**Issue by soberich** [ebean-orm/ebean#1654]
Supersedes https://github.com/ebean-orm/ebean/issues/1650

failing test

```java
public class AppTest {

    @Test
    @Transactional //it works fine if we comment out @Transactional
    public void queryingForDependentWhichDoesNotExistAfterQueryingAggregateEquallyReturnsNullWithinTransaction2() {
        new Aggregate().insert();
        assertNull(Dependent.find.byId(1L));
        new QAggregate().id.eq(1L).findOne(); // or `Aggregate.find.byId(1L);`
        assertNull(Dependent.find.byId(1L)); //expected null, but was:<ebean_issue.Dependent@1> FIXME: where is it from?
    }
}
```

within transaction test fails finding a Dependent entity, while there none of them were persisted.
code attached
[ebean_issue_ 2.zip](https://github.com/ebean-orm/ebean/files/2975811/ebean_issue_.2.zip)

**Comment by soberich** [comment]
@rbygrave in previous issue #1650 the dialog went more vividly, which is unfortunate, because, I agree, that were less precise. But this one, is quite concrete. I basically extracted part of the problem and posted here to be specific.
Is it descriptive enough?

**Comment by rbygrave** [comment]
Ok cool.  I haven't had time to look at it yet - I've still got a few things to work on but hopefully I get to look at it in a few days.  It is just busy at the moment.

**Comment by rbygrave** [comment]
Right so the important part of the model wrt this is:
```java
    @PrimaryKeyJoinColumn
    @OneToOne(cascade = CascadeType.ALL, orphanRemoval = true)
    Dependent dependent;
```
- This is a `@PrimaryKeyJoinColumn`
- This does NOT have `fetch = FetchType.LAZY` (unlike below)

So for example, if the PrimaryKeyJoinColumn was `FetchType.LAZY` ... then the test would pass. That is:
```java
    @PrimaryKeyJoinColumn
    @OneToOne(cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    Dependent dependent;
```

Ok, so what is happening and why etc.

The "PersistenceContext" is by default scoped to the transaction.  So when we have `@Transactional` on this method the persistence context scope spans all the queries in the method and specifically here it spans the last 2 queries:
```java
new QAggregate().id.eq(1L).findOne()
assertNull(Dependent.find.byId(1L));
``` 
...
So the aggregation query does:
```sql
select t0.id, t0.name, t0.id from aggregate t0 where t0.id = ?  ; --bind(1, )
```
Note that the `t0.id` column is included twice in the select clause.  The first for the primary key column and the second time for the foreign key column to dependent.  Now as this is a `@PrimaryKeyJoinColumn` the foreign key column to dependent is in fact the primary key column - hence we select `t0.id` twice (with eager fetching on this property).

Now, when Ebean loads this object graph it puts the beans into the "persistence context".  This means that that 2 beans go into the persistence context:
- A bean for Aggregate with id 1
- A bean for Delegate with id 1 (a reference bean)

So the persistence context contains these 2 beans.  The last query runs and uses that persistence context so ...

```java
assertNull(Dependent.find.byId(1L)); //expected null, but was:<ebean_issue.Dependent@1> FIXME: where is it from?
```
This bean is populated from the persistence context.  It never hits the DB.  With SQL logging we never see the sql query executed for that etc.


# Various alternatives that make the test pass:

1. Remove the @Transactional ... because now the perisistence context doesn't wrap the last 2 queries.  The last query actually hits the DB and there is no row.

2. Map as `@OneToOne(... fetch = FetchType.LAZY)` ... because now the foreign key column is not fetched by default and so that reference bean for dependent 1 is not loaded into the persistence context

3. Execute the last query using QUERY persistence context scope like:

```java
        Dependent one = Dependent.find.query()
          .setPersistenceContextScope(PersistenceContextScope.QUERY)
          .setId(1L)
          .findOne();
```
With this query we execute with it's own persistence context (rather than the one with the transaction that is wrapping the entire method).

Does that make sense?
Cheers, Rob.

**Comment by soberich** [comment]
@rbygrave We never put `fetch = FetchType.LAZY` because it is written in documentation as not advised.
For consistency we would like whether put it everywhere when we would want it (like with JPA) OR nowhere how.
From the internals point of view, would you say it won't introduce that much troubles to put it everywhere where we want it `LAZY`?

**Comment by rbygrave** [comment]
> it is written in documentation as not advised.

To me this is still good advice.  In my opinion the ONLY time where we can desire specifying `fetch = FetchType.LAZY` is for this case of `@PrimaryKeyJoinColumn`.  It is the exception to the rule.

What else do you want to put `FetchType.LAZY` on?  

Cheers, Rob.

**Comment by rbygrave** [comment]
Actually I believe there is generally the second case for `fetch = FetchType.LAZY` which is when we have bi-directional `@OneToOne`.  In this case 1 side of the OneToOne needs a SQL JOIN to fetch the "foreign key value" ... and often we'd like to make that LAZY so as to by default avoid that JOIN (and then we explicitly specify to select the foreign key or explicitly specify a `fetch`.  

So yes, the 2 cases where we consider mapping a relationship with `fetch = FetchType.LAZY` are:
- `@OneToOne with @PrimaryKeyJoinColumn`  (as the foreign key is also the primary key so can be confusion issue - not a performance issue)
- `@OneToOne` on the side without the foreign key (as from a performance perspective we don't want that SQL JOIN by default).

Yes, we should put these notes in the docs for `@OneToOne` ...
