### ISSUE TITLE
For MySql and SQL Server LIKE remove the use of binary keyword / collation

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#1695]
The binary keyword for MySql like was brought in as part of: https://github.com/ebean-orm/ebean/pull/1162/files

We are going to treat the addition of the binary keyword as a bug.  The fix will be to remove the binary keyword from the MySql like cause.

See discussion on google group at:
https://groups.google.com/d/msgid/ebean/c2b9f87c-0983-44bf-a4b4-019fef2baa15%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by rPraml** [comment]
#1162 was introduced by us
We use 'utf8mb4_bin' as DB default in the meantime for all our backend operations (so binary should be used autmatically) - with other collations, like 'utf8mb4_german2_ci' we have strange effects, as 'ä' == 'ae' or 'ss' == 'ß'
We also introduced #1492 so that we can specify special collations when sorting for UI.

I have no objection removing the 'binary' option. But then we should it remove for all platforms (There is a similar workaround in the sqlserver like)
This means:
- like use the db-default collation
- ilike performs a tolower
- the same should count for eq/ieq/...

So, if you using a 'non-case-sensitive' collation (=case-insensitive, like utf8mb4_german2_ci) the result of "like" and "ilike" should be the same. 


Maybe it would be also a good idea to specify the 'ilike' collation in serverconfig, because a tolower(...) is also not always correct (see http://www.moserware.com/2008/02/does-your-code-pass-turkey-test.html)
So: "like" should use DB default collation (which can be case sensitive) and "ilike" should use the one in server-config
