### ISSUE TITLE
Q: how to set multi querybean-packages in ebean.mf  (delimiter)

### ISSUE THREAD

**Issue by weiwill** [ebean-orm/ebean#1781]
My package
system.domain
security. domain

Now I can only set up a package system.domain.

How to set up multiple packages such as 
querybean-packages: system. domain, security. domain 
to generate querybean such as QUser

**Comment by rbygrave** [comment]
The delimiters that can be used are **comma**, **semi-colon** or **space**.  

The following are 3 examples:

Using comma:
`querybean-packages: system.domain,security.domain`

Using semi-colon:
`querybean-packages: system.domain;security.domain`

Using space:
`querybean-packages: system.domain security.domain`

**Comment by weiwill** [comment]
Thank you for your reply

It works.

**Comment by rbygrave** [comment]
Extra notes:

> to generate querybean such as QUser

Note that `querybean-packages` does not specify where the query beans are _generated to_. Query beans are _always_ generated into a `query` sub-package relative to the entity bean that they are generated from. 

### Java
For **Java** `querybean-packages` specify where query beans are being USED.  That is, any code that uses query beans needs to be enhanced. We specify the packages that contain code that USES query beans.  We can completely leave out `querybean-packages` and then all code is checked to see if it uses/calls query beans.

### Kotlin
For **Kotlin** we only need to enhance the query beans themselves.  This difference is because Kotlin has **properties** and Java does not.  So for Kotlin the `querybean-packages` effectively specify packages that the query beans contained in.
