### ISSUE TITLE
Save bean with only *ToMany relations with user generated ID

### ISSUE THREAD

**Issue by frensjan** [ebean-orm/ebean#1783]
When modelling a bean that has only an identifier and *ToMany assocations, Ebean is unable to save an instance of the bean as it is considered a reference bean.

See also #1617.

## Expected behavior
A bean with only an ID should be saved.

## Actual behavior
It isn't saved.

### Steps to reproduce

Model:
```java
@Entity
public class MyBean {

    @Id
    private UUID id;

    @OneToMany(cascade = CascadeType.ALL)
    private List<MyOtherBean> related;

    public MyBean() {
    }

    public MyBean(UUID id) {
        this.id = id;
    }

    ...
}

@Entity
public class MyOtherBean {

    @Id
    public long id;
    ...
}

```

This test fails:
```java
MyBean myBean = new MyBean(UUID.randomUUID());
database.save(myBean);
assertEquals(database.find(MyBean.class, myBean.getId()), myBean);
```

Also this test fails:
```java
MyBean myBean = new MyBean(UUID.randomUUID());
database.insert(myBean);
assertEquals(database.find(MyBean.class, myBean.getId()), myBean);
```

The 'culprit' for inserts seems to be in DefaultPersister.insert(EntityBean, Transaction)`:
```java
  public void insert(EntityBean bean, Transaction t) {
    PersistRequestBean<?> req = createRequest(bean, t, PersistRequest.Type.INSERT);
    if (req.isReference()) {
      // skip insert on reference bean
      return;
    }
    ...
```

**Comment by frensjan** [comment]
Well ... that was uhm, jaw dropping fast if I may say so. Excellent!

**Comment by rbygrave** [comment]
Yeah, well to some extent we have our internals in good shape so we should be able to sort out bugs quickly. It also is good timing at the moment in that my wife has been busy studying a lot so that means I can be home busy coding without being a terrible husband !!

It would be great to be able to allocate more time to Ebean so I'm trying to work something there. Things that help are donations/sponsors as money buys time [off work] and github stars which improves marketing.  So yeah, feel free to give some Ebean project github stars.  I'm going to propose a second level of one off type donation/sponsorship for development teams that want to see Ebean step up a level with documentation / tutorials / examples etc.

Cheers, Rob.
