### ISSUE TITLE
Q: lateinit property users has not been initialized

### ISSUE THREAD

**Issue by weiwill** [ebean-orm/ebean#1799]
```java
QSysRole().fetch("users").users.id.eq("admin").findSet()
```
The above code reports the following error

users is @ManyToMany

```console
  org.springframework.web.util.NestedServletException: Request processing failed; nested exception is kotlin.UninitializedPropertyAccessException: lateinit property users has not been initialized
```
I think my code is the same as the following, except that I used kotlin.

```java
List<Customer> customers =
  new QCustomer()                              // Customer query bean
    .status.equalTo(Status.NEW)
    .billingAddress.city.equalTo("Auckland")
    .contacts.isEmpty()
    .findList();
```
I don't know how to solve it.

**Comment by rbygrave** [comment]
Reference: https://ebean.io/docs/introduction/manifest

Have a look at the ebean.mf file at:    src/main/resources/ebean.mf

... and look for the querybean-packages entry like:

querybean-packages: org.example.myapp.domain


For Kotlin we should specify the package(s) that contain the entity beans
(as the query beans are a sub-package of that and we don't need to enhance
any other code when using Kotlin querybeans).

Let me know if that sorts it out.


Thanks, Rob.

**Comment by weiwill** [comment]
Yes, after adding ebean. mf, it will work properly.
Thank you very much.

**Comment by weiwill** [comment]
When I upgraded the version of ebean to '12.11.4'

I found Enhancement desc for document
![image](https://user-images.githubusercontent.com/3794090/134310823-4969f401-c69b-4e52-be5e-2c3d519a0a48.png)

So I deleted ebean.mf
Then an exception throw for: kotlin.UninitializedPropertyAccessException: lateinit property ...

Do I need other operations to delete the ebean.mf file?

**Comment by rbygrave** [comment]
> Do I need other operations to delete the ebean.mf file?

No, it should not be needed.  Can you create an example app that reproduces the problem?

**Comment by weiwill** [comment]
> > Do I need other operations to delete the ebean.mf file?
> 
> No, it should not be needed. Can you create an example app that reproduces the problem?

[ebean-test.zip](https://github.com/ebean-orm/ebean/files/7221896/ebean-test.zip)

like this project

After I delete the ebean.mf file
clean and run again it's will throw exception `kotlin.UninitializedPropertyAccessException: lateinit property ...`

**Comment by rbygrave** [comment]
Review this example: https://github.com/ebean-orm/examples/blob/master/basic-gradle-kotlin/build.gradle

The ebean-test.zip didn't have any tests. I did notice that it hadn't updated:
- ebeanGradlePluginVersion = '11.39.1'
- ebeanTestConfigVersion = '11.41.2'

And    `testImplementation "io.ebean.test:ebean-test-config:$ebeanTestConfigVersion"` should now be `io.ebean:ebean-test`

The problem is that the ebean gradle plugin needs to be updated. The latest version of the ebean gradle plugin is 12.12.0.  Note that we no longer publish the ebean gradle plugin to maven central and instead only publish it to the gradle plugin repository (which is why I suspect you didn't upgrade it)

**Comment by weiwill** [comment]
1. add `maven { url 'https://plugins.gradle.org/m2/' }` to gradle repositories
2. upgrade ebean-gradle-plugin to 12.12.0
problem solving
thanks
