### ISSUE TITLE
NPE occurred while execute getter operator concurrent

### ISSUE THREAD

**Issue by caoli5288** [ebean-orm/ebean#1851]
## Actual behavior
In ` src/main/java/io/ebean/bean/EntityBeanIntercept.java`
```java
private void preGetterCallback(int propertyIndex) {
    if (preGetterCallback != null) {
        preGetterCallback.preGetterTrigger(propertyIndex);
```

It will throw NPE if save() operator execute concurrent sometimes. `save()` will clear `preGetterCallback` somehow. See
```java
public void clearGetterCallback() {
    this.preGetterCallback = null;
```

I think `getter` is implicit thread safety literally.

### Console

![图片](https://user-images.githubusercontent.com/3120587/68104862-aa6b4c00-ff17-11e9-8a2b-47f7b3b13d09.png)

**Comment by rbygrave** [comment]
> It will throw NPE if save() operator execute concurrent sometimes.

How would that happen?

**Comment by caoli5288** [comment]
@rbygrave Save entity bean in progress and execute any `getter` in other threads may cause this exception.

It happend very rare but terrible.:-(

**Comment by rbygrave** [comment]
The "design" we are talking about is treating a entity bean instance as "thread safe for reading/getters" but at the same time calling save() on that same instance.

This to me is a "design issue".

Entity bean instances CAN be thread safe for multiple readers but not for the case where that bean instance is persisting.  

An entity bean instance that is persisting IS NOT safe for other threads to call getters on.  What is the scenario where this bean instance is being made available for other threads to call getters on?  What are these threads doing?

**Comment by caoli5288** [comment]
I know what you means but ebean should do not thrown an NPE in this case. `not safe` means it may read dirty data not means it will crash application. right?

There is no problem using dirty data in many cases and in fact it's just a single instance application that can't even read dirty data in this case.

**Comment by rbygrave** [comment]
> but ebean should do not thrown an NPE in this case

Ideally Ebean throws a `Please don't do this!! The application is sharing a mutating entity bean!!  Please change the application code design to not do this (share mutating entity beans across threads)`

> not safe means it may read dirty data not means it will crash application, right?

Not safe means `don't do this !!!  please change the application code`.  Other threads calling getters on mutating entity bean means `Failure` and not `maybe read Dirty/Old data`.

It isn't correct thinking/design to have the application think it can share mutating entity beans across threads.  You haven't explain why you think this is a good idea or why the application is doing it ... but no, don't do it.

> I think update current clearGetterCallback() to this.preGetterCallback = DEFAULT_EMPTY_CALLBACK can fix it simple, right?

If this did work it would be hiding a fundamental design issue / incorrect assumption.  

Application code should not be sharing mutating entity beans.  Getters CAN invoke lazy loading which mutates the bean.  Getters ARE safe on non-mutating read only entity beans and Ebean supports that with our read only queries or disabling lazy loading.

**Comment by caoli5288** [comment]
> You haven't explain why you think this is a good idea or why the application is doing it 

Because this is an single instance application that `save()` operator means `just save it to datebase`. This shouldn't caused any problems if I use raw jdbc but ebean thrown an NPE.

I think we should stop talking about my application, and an more obvious fact is that any unexpected NPE is an bug and should be fixed, right?

**Comment by rbygrave** [comment]
> any unexpected NPE is an bug and should be fixed, right?

Not if a 'fix' comes with excessive cost or complexity and is extremely rare.

**Comment by rbygrave** [comment]
Remember this issue currently has no failing test case, and as far as I know it has no known application scenario where this NPE should reasonably occur.

**Comment by caoli5288** [comment]
So an scheduled async save task should block all getter? How should we do? Or you means we should never schedule save task to threads?

> Not if a 'fix' comes with excessive cost or complexity and is extremely rare.

This fix is excessive cost or complexity?

**Comment by rbygrave** [comment]
It is about sharing entity bean instances (that mutate) across multiple threads.

>  we should never schedule save task to threads?

No problem as long as the entity bean instances are not shared.  It isn't clear why your application code is sharing entity bean instances.

**Comment by rbygrave** [comment]
This issue can't progress with out more details around how and why entity bean instances that are being saved are shared by multiple threads.

The assumption is that this is an application code issue.  I'll close this.

Reopen if you want to provide more information.

Thanks.

**Comment by jnehlmeier** [comment]
@rbygrave one example would be a simple application that does background saving (e.g. once every 30 seconds) in a dedicated thread and the application is also fine with that entity being updated by the UI concurrently typically within the UI thread.

Wondering what the JPA spec says about concurrent read/write of an entity.

**Comment by rbygrave** [comment]
> Wondering what the JPA spec says about concurrent read/write of an entity.

EntityManager isn't thread safe. I'm pretty sure there isn't anything saying entity instances are thread safe (as they are somewhat owned by an EntityManager instance). 

> a simple application that does background saving (e.g. once every 30 seconds) in a dedicated thread and the application is also fine with that entity being updated by the UI concurrently typically within the UI thread.

You need to flesh out your simple example more specifically wrt entity **instances**. The same **instance** of an entity bean shared by 2 threads both persisting that same instance - no!! Use 2 instances and optimistic locking or pessimistic locking.  

By all means fresh out your example more but ... "_no sharing of a mutating/persisting entity bean instance_" is the rule and there is no known valid scenario for breaking that rule (but maybe one day someone will provide one).

I believe @caoli5288 felt that "getters" on a mutating entity bean were "safe" in that they were "atomic" (which is reasonable on non entity beans but unfortunately not for entity beans). At least my understanding of this question is it valid for other threads to call "getters" (with atomic results) with only a single thread owning the "persisting" of the instance. I'm saying that isn't correct because "getters" on entity beans can actually indirectly invoke mutating of the instance via invoking persisting via preGetterCallback and lazy loading (which wouldn't occur on a "new instance/non loaded instance").

Thread safety on an entity bean "getters only" would require that we guarantee no lazy loading or preGetterCallback invocation.  Hence the question somewhat leads to ... should preGetterCallback be atomic / we not see a NPE in the high contention case.

The NPE above line 851 isn't valid in current code, I'm not sure the version that was being used to get the NPE. I believe this matches line 919 in current EntityBeanIntercept code. My guess for this NPE is that there is a race condition between 2 threads on the same instance where a getter and save() are called concurrently.
