### ISSUE TITLE
Ebean 12.1.9 breaks Guice in Stage.PRODUCTION mode for multi tenant apps

### ISSUE THREAD

**Issue by jnehlmeier** [ebean-orm/ebean#1918]
## Expected behavior

No Guice injection error should be thrown when *.war file deployed to Jetty.

## Actual behavior

During Jetty deployment the `GuiceServletContextListener` will be executed to create the Guice Injector. The injector can be created in two different stages/modes: `Stage.DEVELOPMENT` and `Stage.PRODUCTION`. In production stage Guice will create eager singletons and normal singletons up front and also does other checks to make sure injection issues are catched during deployment rather than at runtime. Thats the stage/mode we currently use in production.

Since we let Guice create an instance of Ebeans `Database` interface we have a `MultiTenantDatabaseProvider` implementation that creates a `DatabaseConfig` in multi tenant mode (db per tenant). Our implementation of Ebeans `CurrentTenantProvider` has a Guice provider injected that can provide the `currentId()`  tenant id value during a HTTP request (since only the HTTP request can tell us which tenant currently works with our app). So it basically looks like

```java
@Override
public Object currentId() {
  return tenantProvider.get(); // Guice request scoped provider. Fails during deployment.
}
```

With EBean 12.1.9 the constructor of `DefaultServer` now creates a datasource through the `TransactionManager`: https://github.com/ebean-orm/ebean/blob/3127bc21547161fb3139ab0bae6682aa64503c4f/src/main/java/io/ebeaninternal/server/core/DefaultServer.java#L296

So during Jetty deployment, the Injector will be created, which in turn will create the Database singleton which in turn tries to get a datasource and causes a call to `CurrentTenantProvider.currentId()` at deployment time. This fails because our provider implementation to provide that value can only work at runtime during a HTTP request.

### Steps to reproduce

Requires quite a bit of code, so I'll omit it for now. But I could provide some, if you can not follow the above description.

### Workaround

Currently we can only use 12.1.8 or we change the Guice stage from PRODUCTION to DEVELOPMENT so that singletons are created on first use, rather than at deployment time.

I think we will stay on 12.1.8 for now, since we don't want possible injection issues to occur at runtime.

**Comment by rbygrave** [comment]
Nice description, I understand the issue - thanks.

> constructor of DefaultServer now creates a datasource through the TransactionManager line 296

Right. We can work around this by having QueryPlanManager depend on TransactionManager rather than DataSource.  

The background here is that the QueryPlanManager needs to get a java.sql.Connection in order to collect query plans in the background.  This isn't going to work for this `MultiTenantDatabaseProvider` case in that there won't be a currentTenantId available so this is probably something to sort out in the future (query plan collection for the MultiTenantDatabaseProvider case).

**Summary:**
They change we want here to fix this is to change QueryPlanManager to depend on TransactionManager rather than DataSource (and hence not access DataSource until query plan collection - understanding that currently that isn't going to work in the MultiTenantDatabaseProvider case.
