### ISSUE TITLE
@History it seems does not work well when it got generated with ebean.allQuotedIdentifiers enabled

### ISSUE THREAD

**Issue by almothafar** [ebean-orm/ebean#1941]
I'm trying to know more about ebean feature and found `@History` that might be helpful for auditing, but when I added it to the entity the generated code was wrong, it is a clear issue it seems, that `@History` got generated in evolution script wrongly with `ebean.allQuotedIdentifiers` set to `ture`:

## Expected behavior
I'm not sure, I'm a little confused regarding https://ebean.io/docs/features/history the table should be [Customer] not [Customer_history] or should be? or should be 2 tables? if so why evolution generates for `Customer` but not for `Customer_history`? 

I guess `_history` should not be there in the first place, isn't?

## Actual behavior
The name of the table called `[Customer]_history` the up version is:

```sql
alter table [dbo].[Customer]
    add sys_periodFrom datetime2 GENERATED ALWAYS AS ROW START NOT NULL DEFAULT SYSUTCDATETIME(),
        sys_periodTo   datetime2 GENERATED ALWAYS AS ROW END   NOT NULL DEFAULT '9999-12-31T23:59:59.9999999',
period for system_time (sys_periodFrom, sys_periodTo);
alter table [dbo].[Customer] set (system_versioning = on (history_table=[dbo].[Customer]_history));
```

And down part generated to: 
```sql
IF OBJECT_ID('[dbo].[Customer]_history', 'U') IS NOT NULL drop table [dbo].[Customer]_history;
```

**Comment by rbygrave** [comment]
This is SQLServer so it uses a history table which can be auto created with an 'interesting/hard to identify name' _or_ we can specify the history table name which is what we want to do.

The problem here is that the Ebean generated ddl is explicitly specifying the history table name as `[Customer]_history` which is invalid/not correct and instead it should be `[Customer_history]`.  

We prefer to have a reasonable name for the history table than have SQLServer generate the history table name in the form: 
`MSSQL_TemporalHistoryFor_<current_temporal_table_object_id>_[suffix]`. 
... where suffix is optional and it will be added only if the first part of the table name is not unique.

Reference: https://docs.microsoft.com/en-us/sql/relational-databases/tables/creating-a-system-versioned-temporal-table
