### ISSUE TITLE
NullPointerException in EntityBeanIntercept

### ISSUE THREAD

**Issue by tobias-** [ebean-orm/ebean#1980]
## Expected behavior
Clean execution.

## Actual behavior
Works more than 99.9% of the times, *rarely* a stacktrace with NPE. Approx once every >1'000 execution fails.
I don't think I've seen it more than one time for any unique test case. We have not upgraded production yet, so this is only in tests.

### Steps to reproduce

Not sure. I *suspect* a race condition, but we are completely unable to reproduce it reliably.

We do NOT have any pre-getter interceptors registered, but one IS attached (internal ebean hook).

Could it be because we do multiple saves on the same object instance?
Another possible reason it happens for us is that in tests we do 
`serverConfig.backgroundExecutorSchedulePoolSize = 1`, because we want to make sure all background tasks have been finished before moving on to the next test.

The code that blows up is trivial:
```kotlin
        if (bean.deleted) {
```

```console
Stacktrace
java.lang.NullPointerException
	at io.ebean.bean.EntityBeanIntercept.preGetterCallback(EntityBeanIntercept.java:917)
	at io.ebean.bean.EntityBeanIntercept.preGetter(EntityBeanIntercept.java:932)
	at OurDBO._ebean_get_deleted(OurDBO.kt:999)
	at OurDBO.getDeleted(OurDBO.kt:999)
	at OurBeanPersistListener.inserted(OurBeanPersistListener.kt:999)
	at io.ebeaninternal.server.core.PersistRequestBean.notifyLocalPersistListener(PersistRequestBean.java:565)
	at io.ebeaninternal.server.transaction.PostCommitProcessing.localPersistListenersNotify(PostCommitProcessing.java:160)
	at io.ebeaninternal.server.transaction.PostCommitProcessing.lambda$backgroundNotify$0(PostCommitProcessing.java:134)
	at io.ebeaninternal.server.core.DefaultBackgroundExecutor.lambda$execute$0(DefaultBackgroundExecutor.java:43)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)```

**Comment by tobias-** [comment]
Forgot to say we're using version 12.2.1.

**Comment by rbygrave** [comment]
I don't think this is a race condition in that the clearGetterCallback() happens early (before persisting and that is before any listener callback / OurBeanPersistListener) SO ...

I think it is that preGetterCallback should be **_volatile_** ... my theory, the bg thread is reading the field twice, the first time reads a memory local reference that isn't null and reads second time getting null ... so the theory is that volatile will make it fully read memory wise - aka java memory model.

**Comment by rbygrave** [comment]
Hi @tobias-  can you try to reproduce with ebean version 12.2.2 (which has the volatile modifier).

Thanks, Rob.

**Comment by tobias-** [comment]
Yes, I will try that. I think the problem will still exists, as the JVM IS reading the field twice and not caching it (which is what I think the volatile is used to avoid). What is necessary to avoid it is a temporary variable (e.g. similar to what the construct `x?. let { it.run() }` does, but my main concern is that this will just hide the problem as the pre-getter will not be called reliably if two threads are using the same object instance. Is that a known limitation?

**Comment by tobias-** [comment]
Unfortunately, it still happens with the volatile setting.

**Comment by rbygrave** [comment]
Ok. Are you able to build Ebean locally?  Do you want to try a local variable?

**Comment by tobias-** [comment]
Yes, I have no problems testing with local builds, just either point me towards a branch or give me patches. Just be aware I'm on UTC+1 (06:30) so I'm not quite awake yet :).

I'll try that, but if it itsn't necessary, why is the preGetterCallback used?

**Comment by tobias-** [comment]
What I mean is, should the field be a ThreadLocal, if it is used as such?

**Comment by rbygrave** [comment]
It doesn't need to be threadlocal no.  I can explain more later.  Just
dinner time and getting convid19 lockdown news for NZ.  UTC+13. :)

**Comment by tobias-** [comment]
UTC+1 here, so I'm still not quite awake :)  Works well now it seems.

Either way, I'll send a PR for the change. This visualizes the problem pretty well though:

![image](https://user-images.githubusercontent.com/1174699/77505928-ce96dd80-6e64-11ea-859a-f1eba02a69c6.png)

**Comment by rbygrave** [comment]
So my thinking here is:
- Bean is inserted in a transaction with jdbc batch (so preGetterCallback set, cleared on flush)
- The insert triggers the `at OurBeanPersistListener.inserted(OurBeanPersistListener.kt:999)` ... but it will occur in the background
- The same instance is persisted a second time as an update with jdbc batch (so preGetterCallback set, cleared on flush)

The OurBeanPersistListener is now in a race with the second persist on the same instance. The is read and is not null (set by the update) and is read again shortly after and now was null (because it was cleared by the update being flushed).  

So we had some options. 1 option was to read the preGettterCallback into a local field (which was the fix PR). 

Another option would be to be move PostCommitProcessing.localPersistListenersNotify() from the background into the foreground (maybe as an option on the transaction or globally). We have this type of option with L2 cache notification (to be foreground or background based on serverConfig.isNotifyL2CacheInForeground()).

At this stage my thinking is to not go down this track and keep localPersistListenersNotify() as something that occurs in the background with the thought that we rarely have this race (persist the same instance twice in 2 transactions with a BeanPerisistListener) and that using a local variable is a reasonable fix.

**Comment by tobias-** [comment]
Thanks for the explanation!

**Comment by rbygrave** [comment]
No worries.  I may as well add in here: 

Q: What is this preGetterCallback thing anyway?

A: When we persist a bean using JDBC batch it is not actually persisted immediately but instead is "queued / buffered" (in a slightly interesting way because we need to maintain ordering and batch the same beans together by "type", "persist type" and "depth").

When we do this Ebean hasn't yet actually persisted the bean so generated properties like `@Id`, `@WhenCreated` etc have not actually been persisted and populated yet (_unlike in non-batch mode_).

If the application code now calls a getter or setter (e.g calls `bean.getId()` ) ... the preGetterCallback is used to trigger a JDBC batch flush. In this way the application code would see no difference between JDBC batch and non-batch mode. We can turn on JDBC batch without impacting the application code/logic.

----
**Summary:**

- Setting preGetterCallback gives us an implicit batch flush if a getter or setter is called on a batched  persist request
- The preGetterCallback is cleared when the flush occurs and the bean is truely persisted (statement executed)
