### ISSUE TITLE
How to change mapped SQL type for LocalDateTime when generating DB migrations

### ISSUE THREAD

**Issue by ooooo84** [ebean-orm/ebean#2039]
I'm using PostgreSQL 11.7, when i generate DB migration SQL scripts, Ebean always use SQL type timestamptz for LocalDateTime even i have set @Column(columnDefinition = "timestamp")

## Expected behavior
Want to set LocalDateTime mapped to timestamp SQL type

## Actual behavior
LocalDateTime mapped to timestamptz

### Steps to reproduce

```java
    @Column(columnDefinition = "timestamp")
    private LocalDateTime publishedOn;
```

```console
  // some logging output
```

**Comment by rbygrave** [comment]
I am still pondering this.

**Comment by jnehlmeier** [comment]
@rbygrave We also use `timestamp` without timezone in your DB for all Date, LocalDateTime fields. Reason is all our customers are in the same timezone as our company and all our operating systems / software are configured to use that timezone.

**Comment by rbygrave** [comment]
FYI: I am still pondering the approach here. With our DB migrations we have "logical types" and then "platform specific types".

For example we can have logical type like json(1000) which might translate into varchar(1000) on H2 and JSON on PG.  We have these "logical types" so that we can generate multi-platform DDL of the same logical model/diff etc.

Now the issue as I currently see it is that ideally we have a distinction between "timestamp" and "timestamp with timezone" ... in terms of _logical types_.  Right now logical "timestamp" pretty much translates to "timestamp with timezone".  This is the source of the reason why `@Column(columnDefinition="timestamp")` works in create-all.sql ddl generation but not really via DB migrations [as logical "timestamp" get translated into "timestamptz" for PG for example].

It might be nice for the logical model to have "timestamptz" and "timestamp local" ... but everyone out there has logical models with "timestamp" in them (and those map to timestamptz).  Still pondering ...

**Comment by rbygrave** [comment]
Right looking to push a solution for this.

Java LocalDateTime will map to an extra data type which in Postgres maps to `timestamp`.  So given we have a model like:

```java
@Identity(cache = 1000)
@Entity
@Table(name = "customer")
public class DCustomer extends Model {

  @Id
  long id;

  @Length(50)
  final String name;

  LocalDateTime localWhen;

  Instant instantWhen;
  ...
```

The logical migration model will use `localdatetime` as the logical type for `localWhen` so we see the model.xml as:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<migration xmlns="http://ebean-orm.github.io/xml/ns/dbmigration">
    <changeSet type="apply">
        <createTable name="customer" identityCache="1000" pkName="pk_customer">
            <column name="id" type="bigint" primaryKey="true"/>
            <column name="name" type="varchar(50)"/>
            <column name="local_when" type="localdatetime"/>
            <column name="instant_when" type="timestamp"/>
            <column name="version" type="bigint" notnull="true"/>
        </createTable>
    </changeSet>
</migration>
```

We see generated Postgres DDL as:

```sql
-- apply changes
create table customer (
  id                            bigint generated by default as identity (cache 1000) not null,
  name                          varchar(50),
  local_when                    timestamp,
  instant_when                  timestamptz,
  version                       bigint not null,
  constraint pk_customer primary key (id)
);
```
