### ISSUE TITLE
Docs issue: deprecated ServerConfig and ServerConfigStartup 

### ISSUE THREAD

**Issue by almothafar** [ebean-orm/ebean#2049]
I was configuring the Ebean server before with implementing `ServerConfigStartup` and add it to the models path so it takes the configuration when the server starts, now what I see it deprecation message for `ServerConfig` while `ServerConfigStartup` still OK?

```java
package models;

import com.zaxxer.hikari.HikariDataSource;
import exceptions.ApplicationException;
import io.ebean.config.ServerConfig;
import io.ebean.config.dbplatform.IdType;
import io.ebean.config.dbplatform.sqlserver.SqlServer17Platform;
import io.ebean.event.ServerConfigStartup;

import java.sql.SQLException;

public class EbeanServerConfigStartup implements ServerConfigStartup {
    public void onStart(ServerConfig serverConfig) {
        try {
            final String driverClassName = serverConfig.getDataSource().unwrap(HikariDataSource.class).getDriverClassName();
            if ("com.microsoft.sqlserver.jdbc.SQLServerDriver".equals(driverClassName)) {
                serverConfig.setDatabasePlatform(new SqlServer17Platform());
                serverConfig.setIdType(IdType.IDENTITY);
                serverConfig.setLazyLoadBatchSize(50);
            }
        } catch (SQLException ex) {
            throw new ApplicationException(ex.getMessage(), ex);
        }

    }
}
```

I got another project that I do use `application.properties` instead of this, but I wanted to see if there is a replacement for this, I see it is mentioning using `DatabaseFactory`, but there is no doc page for how to use that!

https://github.com/ebean-orm/ebean/blob/master/src/main/java/io/ebean/config/ServerConfig.java#L81-L87

+ this is NOT deprecated: https://github.com/ebean-orm/ebean/blob/master/src/main/java/io/ebean/event/ServerConfigStartup.java 

+ Also in Doc what mentioned now are the old deprecated method:

https://ebean.io/docs/setup/guice

Is there a replacement that can override what already configured like what I was doing before?

P.S: I might know the answer, with creating a module and get the current server and configure it, not sure if that would work as I'm moving my config to `application.properties` anyway, but wanted to see if you have a better way.

**Comment by rbygrave** [comment]
I do need to ponder this a bit but I believe we should add a DatabaseConfigStartup that uses DatabaseConfig (and deprecate ServerConfigStartup).  I have looked at this in the past but didn't actually add a DatabaseConfigStartup in case I came up with a better approach (like ServerConfig extend DatabaseConfig rather than the other way around) but that didn't really work out and I didn't come back to this.

At this stage I believe we should add a DatabaseConfigStartup.

Note that the full removal of ServerConfig/EbeanServer/Ebean in favour of DatabaseConfig/Database/DB is some way off as in maybe 1 year.  We want the majority of people to be up on 12.x and migrated away from ServerConfig/EbeanServer/Ebean before we remove them. 

Cheers, Rob.
