### ISSUE TITLE
Enhancement can not create equals, hashCode function

### ISSUE THREAD

**Issue by batzorigt** [ebean-orm/ebean#2095]
## Expected behavior
Identity - equals/hashCode
Do not implement equals() and hashCode() on @Entity beans (but instead leave that to Ebean enhancement).

Ebean will enhance entity beans with an optimal implementation of equals() and hashCode() and we should not try and do better and instead just leave it to Ebean.

## Actual behavior
Query bean is generated, but for @Entity beans equals() and hashCode() are not generated.

**Comment by rbygrave** [comment]
> Query bean is generated, but for @entity beans equals() and hashCode() are not generated.

"Query beans" are not "Entity beans".  There is no need or expectation to add equals/hashCode to query beans.  Behaviour is as expected.

This is a misunderstanding right?

Cheers, Rob.

**Comment by batzorigt** [comment]
Please read best practis: - https://ebean.io/docs/best-practice

**Comment by jnehlmeier** [comment]
I think the issue might be that Ebean now marks all generated code as synthetic. This has been done for JaCoCo test coverage. However when opening/decompiling a class file in, e.g. IntelliJ, the generated code is not visible  which can leave the impression that is hasn't been generated. 

It is actually a bit annoying when debugging code because there is no way to look at the generated code produced by Ebean.

**Comment by rbygrave** [comment]
Hi @batzorigt   I'll close this issue at this stage. You can re-open if you want to clarify what you are trying to say with this issue but Ebean is enhancing entity beans with equals() and hashCode() implementation.

Thanks.
