### ISSUE TITLE
Add query.findFirst() method [vs use query.setMaxRows(1).findOneOrEmpty() ] 

### ISSUE THREAD

**Issue by qq1056125478** [ebean-orm/ebean#2176]
findFirst reduces the amount of data obtained by db by limiting setRowMax(1) to speed up the query.

Contact contact =
  new QContact()                               
    .email.equalTo("rob@foo.com")             
    .findFirst(); 
	
**Equivalent to**
	
Contact contact =
  new QContact()                               
    .email.equalTo("rob@foo.com")        
	.setRowMax(1)
    .findList()
	.get(0);

**Comment by rbygrave** [comment]
Right now people would be using:

query...
  .setMaxRows(1)
  .findOne() / findOneOrEmpty()

Why do we need findFirst() ?  It is not clear to me why we need to add it.

Cheers, Rob.

**Comment by rbygrave** [comment]
So to be clear I am NOT expecting people to do use the `.findList().get(0);` part but I am instead expecting people to use `.findOne()` or `.findOneOrEmpty()` along with the setMaxRows(1) like:

```java
Contact contact =
  new QContact()
    .email.equalTo("rob@foo.com")
    .setRowMaxs(1)
    .findOne();
```
So I don't see the big need for `findFirst()` ?

**Comment by qq1056125478** [comment]
findFirst() is equivalent to a syntactic sugar to reduce the data transmission of findOne() database,
If the frequency of use is not high, there is really no need to join, we can completely pass setMaxRows(1), thanks for the reply.

**Comment by qq1056125478** [comment]
> So to be clear I am NOT expecting people to do use the `.findList().get(0);` part but I am instead expecting people to use `.findOne()` or `.findOneOrEmpty()` along with the setMaxRows(1) like:
> 
> ```java
> Contact contact =
>   new QContact()
>     .email.equalTo("rob@foo.com")
>     .setMaxRows(1)
>     .findOne();
> ```
> 
> So I don't see the big need for `findFirst()` ?
> 
> ## How common is "findFirst" use?
> For some background thinking. If the result is expected to be unique based on predicates (say email is unique) then we really ought to use findOne() without any setMaxRows(1). This throws an exception if more than 1 row is returned (which should never happen because it is logically unique).
> 
> The implication is that "findFirst()" approximately means find the first _random_ row given the predicates. As such I believe "findFirst()" is pretty rarely used - there will be a lot of applications that don't ever need to find the first "almost random" row.

For findone (), it is suggested to add setmaxrows (2) automatically to avoid loading too much data into memory;

In response to the findOne() you mentioned, it is recommended to automatically add setMaxRows(2) to avoid unknowing users from calling methods and loading too much data into memory

![image](https://user-images.githubusercontent.com/30294451/108851844-d84e3580-761f-11eb-8ede-22e537f1ddf8.png)

**Comment by rbygrave** [comment]
> In response to the findOne() you mentioned, it is recommended to automatically add setMaxRows(2)

Well no.  IF you need findFirst() ... then implement that as `setMaxRows(1).findOne()`


> This is just my suggestion

No, that isn't a thing we will do.  

If we have a look at extractUnique() and we will see that it throws the NonUniqueResultException() if there are more than 1 result.  That is, we can ONLY use findOne() if the result is 0 or 1 results - it will throw an exception otherwise.  We can only use findOne() in this way and hence we never expect Ebean to add setMaxRows(1) to be an advantage (because the predicates imply a unique result).

So there is no need or requirement for findOne() itself to internally add setMaxRows(1).

The discussion about using  `setMaxRows(1).findOne()` was about more about NOT using `setMaxRows(1).findList().get(0)` - that is instead of findList() get(0) just use findOne because we know there is max 1 result.


So, "findOne" implies that the predicates [or use of setMaxRows(1)] determine that there shall only be maximum 1 result.    Where as "findFirst" implies that there could be many results matching the predicates but we are only interested in the first one.

Also noting that we don't desire the use of setMaxRows(1) when we don't need it as it is a relational/sql limiter (applies to rows and not "graphs").  That is, it stops us using join based fetching of `@OneToMany` or `@ManyToMany` associations (and instead these must be automatically converted to query joins (aka "fetchQuery").  

Hmmm.  Are there people out there keen on adding a `findFirst()` ? as a convenience for `setMaxRows(1).findOneOrEmpty()` ?  Would it assist in reducing confusion?

**Comment by qq1056125478** [comment]
Yes, I forgot to consider @OneToMany@ManyToMany, thanks for the reminder
