### ISSUE TITLE
Fetch on nested one-to-many collections results in duplicates

### ISSUE THREAD

**Issue by bkempe** [ebean-orm/ebean#2179]
Using fetches on one-to-many collections under a many-to-one, e.g.

```java
find(Parent.class)
      .fetch("child")
      .fetch("child.grandchildren")
```

results in the grandchildren containing duplicates because a join is used and not deduped in Ebean.

## Expected behavior

No duplicates in the nested collections.

## Actual behavior

Duplicates found in the nested collections.

### Steps to reproduce

https://github.com/ebean-orm/ebean/pull/2178

### Environment

Ebean 12.7.1

### Workaround

use `fetchQuery`

But the existence of this issue most likely makes relying on auto-tune for nested collections problematic.

**Comment by rbygrave** [comment]
As it is kind of lost in the noise above:

The first fix for this issue was: https://github.com/ebean-orm/ebean/commit/6acf93c97804deba3e7e54fcbeae4a41ded8b88a

The better fix was ultimately: https://github.com/ebean-orm/ebean/pull/2180/files#diff-458eed336791c1656cdb0032219d70c67f76f95eab6ffab02fd7ae318f792da5R28-R35
