### ISSUE TITLE
Generated sql for @WhenModified column always not null while it should be nullable by default

### ISSUE THREAD

**Issue by almothafar** [ebean-orm/ebean#2189]
When I try to add a column for the modification date using `@WhenModified` annotation, the generated code by default set that column as `not null`, even if I explicitly add `nullable = true` it is still ignoring it.

And when I apply the generated code without modification and add a new record using `insert()` it is failing with exception from DB `Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot insert the value NULL into column 'RecordModifiedDate', table ... ect `

The reason for this that I specify `insertable = false` so I don't really want a modification date on "insert" as it is just a new version that not "modified" yet.

### Steps to reproduce

```java
    @Column(name = "RecordModifiedDate", columnDefinition = "datetimeoffset", insertable = false, nullable = true)
    @WhenModified
    private ZonedDateTime modifiedDate;
```

Generated script: 

```sql
create table [dbo].[TableName] (
  [Id]                          integer identity(1,1) not null,
-- Properties
  [RecordCreatedDate]           datetimeoffset not null,
  [RecordModifiedDate]          datetimeoffset not null,
  [Version]                     integer default 1 not null,
  constraint [pk_TableName] primary key ([Id])
);
```

**Comment by rbygrave** [comment]
> explicitly add nullable = true it is still ignoring it.

That really is not explicit though in that `@Column(nullable = true)` is not explicit as the default value of nullable is true (so it is the same as nullable being absent).

> And when I apply the generated code without modification

It isn't clear what you mean here.  What generated code? DDL? If so you have not shown it in the issue above right?


Note that as far as I see it `@WhenModified` is always a non nullable column and I am unlikely to loosen that up (allow null) for it.

**Comment by jnehlmeier** [comment]
> Note that as far as I see it `@WhenModified` is always a non nullable column and I am unlikely to loosen that up (allow null) for it.

What @almothafar is saying is that he wants `@WhenModified` to only apply to real row updates and not row inserts. For him an insert is not a modification of a row.

Thus he tried to use `@Column(insertable = false, nullable = true, updatable = true)`  together with `@WhenModified` and hoped that Ebean respects the `@Column` configuration. 
That is: 
1. Generated DDL should have a nullable column for `modifiedDate` because of the `@Column` configuration
2. Ebean should only update the column value for SQL UPDATE queries but not for SQL INSERT queries because of the `@Column` configuration

Or more simply: He wants `@WhenCreated` for inserts only and `@WhenModified` for updates only. Currently `@WhenModified` also applies for inserts and you can not tell Ebean to not apply it to inserts.

**Comment by rbygrave** [comment]
> he wants @WhenModified to only apply to real row updates and not row inserts.

Ah I see.

>  Currently @WhenModified also applies for inserts and you can not tell Ebean to not apply it to inserts.

Yes `@WhenModified` works like that by design.  I guess I need to hear the use case that wants nulls on insert for WhenCreated.

**Comment by rbygrave** [comment]
To clarify the current state of this issue. `@WhenModified` is working by design and it is expected to be non-nullable and we can't change that via `@Column(nullable=true, insertable=false) - this is effectively the expected behavior and not an accident/bug.

What we are waiting for is more explanation/justification of the use case desiring `@WhenModified` to be nullable and not part of insert. What is the justification for needing that. 

Cheers, Rob.

**Comment by almothafar** [comment]
I think the idea is about a record is added but not modified yet, that's why I think `@WhenModified` can be nullable when you have `@WhenModified` and `@WhenCreated` both will have the same value which is not really useful as I see if I need to know fields that not modified yet I simply can see anything not have modification date.

If you want to keep it not null that's ok, but maybe let me have the option to make it nullable maybe?

**Comment by rbygrave** [comment]
I am unconvinced.  Tell me more about exactly about your use case that needs it to be nullable.

**Comment by rbygrave** [comment]
To add some more comments:
- NULL is not our 'friend'.  We would only make `@WhenModified` nullable because we _absolutely_ need to. 
- I don't want people to make `@WhenModified` nullable and then regret it (and I absolutely think people will regret it)
- I have not hit a case where it is desirable or necessary for `@WhenModified` to be null. That is 30+ years of not hitting an exception to this 'rule'. I'm open for this to be challenged and absolutely someone might well have an exception to this 'rule' but I want to know what is making you think that this is a good idea or something you need?

Cheers, Rob.

**Comment by almothafar** [comment]
I wanted to post my case but I'm out of energy, I'll close this, thank you.

**Comment by rbygrave** [comment]
> I'm out of energy

I feel for you - I think we have all been there at various times and it's tough.  I'll send you some positive energy from New Zealand as we have a bit extra here after just winning the America's Cup (Yacht racing).  Feel free to add comments and re-open when you can.

Cheers, Rob.
