### ISSUE TITLE
Feature request/question: Query execution time for debugging 

### ISSUE THREAD

**Issue by almothafar** [ebean-orm/ebean#2268]
I'm not sure if that does exist or not, but maybe will be nice to add execution time for each query that is executed with debugging info, maybe as a `trace` level or `debug` level.

## Expected behavior
Maybe can be done like:

```console
[debug] - io.ebean.SQL - txn[] select t0.[ID], t0.[FullName], t0.[Column1], ... etc from [dbo].[SomeTable] t0 where t0.[Id] = ?; --bind(2500) --time(756ms)
```
Or maybe that is impossible printing statement is done before the execution, so that statement can be repeated with time, I'm not sure actually if there is any good idea, like.

```console
[debug] - io.ebean.SQL - txn[] select t0.[ID], t0.[FullName], t0.[Column1], ... etc from [dbo].[SomeTable] t0 where t0.[Id] = ?; --bind(2500) --txnid(2fasf2312e1xa)
OR
[debug] - io.ebean.SQL - txn[2fasf2312e1xa] select t0.[ID], t0.[FullName], t0.[Column1], ... etc from [dbo].[SomeTable] t0 where t0.[Id] = ?; --bind(2500)

[debug] - io.ebean.SQL - txn[2fasf2312e1xa] executed in 756ms
```

## Actual behavior
Currently, it is logging like:

```console
[debug] - io.ebean.SQL - txn[] select t0.[ID], t0.[FullName], t0.[Column1], ... etc from [dbo].[SomeTable] t0 where t0.[Id] = ?; --bind(2500)
```

### Steps to reproduce
Logback logging enabled to `io.ebean.SQL` to `debug` level:

```xml
    <logger name="io.ebean.SQL" level="DEBUG"/>
```

**Comment by jnehlmeier** [comment]
You can provide Ebean a datasource that is wrapped with a custom datasource (delegate pattern) that  in turn wraps connection and prepared statement to track execution times and log them. This can also be used to implement some aggregating metrics that are pushed regularly to some time series database like influxdb.

**Comment by rbygrave** [comment]
Well, if we turn on summary level logging we get the execution times `io.ebean.SUM` but ...

Actually the recommendation is to use the metrics that Ebean is already collecting and is made available via:  

```java
    ServerMetrics metrics = DB.getDefault().getMetaInfoManager().collectMetrics();
    for (MetaQueryMetric metric : metrics.getQueryMetrics()) {
      System.out.println(metric);
    }

    System.out.println("-- transaction metrics --");
    for (MetaTimedMetric metric : metrics.getTimedMetrics()) {
      System.out.println(metric);
    }
```

So this includes aggregated execution metrics for query execution, transactions as well as L2 cache etc (well, all the metrics that we deem important).

This is built with the view that we get these metrics say every 1 minute and then push those metrics to something like influxdb.  This is what "ebean insight" is looking to do plus a couple of other things like collect query execution plans etc (but you can't use ebean insight just yet, it's still in closed beta).

So should we log the execution timing in the logging?  I don't feel this is the right thing really - aggregated metrics are pretty much what we want + something like "profiling" / open telemetry (which Ebean also has but it isn't ideal and not documented). I've got github issues for adding the docs for these things.  In a previous discussion on the google group I think we discuss how the profiling should improve to support open telemetry.

Anyway, the recommendation is to periodically pull the metrics from `MetaInfoManager` ... via `database.getMetaInfoManager().collectMetrics()`.  Have you looked at that?  (I suspect you were not aware of it)

**Comment by rbygrave** [comment]
> custom datasource (delegate pattern) that in turn wraps connection

To me this isn't ideal in terms of metrics "keys" and relating the query metrics back to source code.  If people use query beans then via enhancement we link all the query execution metrics back to the line of code that executes the query plus imo much nicer "keys" for the metrics.  

Have you looked at the metrics from MetaInfoManager and still chosen to use the delegating DataSource approach?  I'd be interested to here why etc.

Cheers, Rob.

**Comment by jnehlmeier** [comment]
> > custom datasource (delegate pattern) that in turn wraps connection
> 
> To me this isn't ideal in terms of metrics "keys" and relating the query metrics back to source code. If people use query beans then via enhancement we link all the query execution metrics back to the line of code that executes the query plus imo much nicer "keys" for the metrics. If we are not using query beans we get OK metrics keys but we can use `query.setLabel(...)` to give each query a good label (to relate it back to code).
> 
> Have you looked at the metrics from MetaInfoManager and still chosen to use the delegating DataSource approach? I'd be interested to hear why you like that approach better etc.

When you calculate a key based on the query and its source code location then you generally have an endless amount of different keys over time (lots of different queries, code refactors can change stack information). However time series databases like Influxdb are sensitive to cardinality, which means when you index a column by making it a tag (so you can group metrics by that tag) and that column contains an endlessly increasing amount of different values you are increasing cardinality. This hurt memory consumption and performance of InfluxDB. See: https://docs.influxdata.com/influxdb/cloud/write-data/best-practices/resolve-high-cardinality/

Given that we have a multi tenant application with each tenant and have tagged the tenant id, we already have such an increasing tag, however it increases slowly. So every other measurements we record are already `<tenant-count> * <remaining cardinality>`.  Add to that tags for an increasing number of app servers and for an application name/version. Also slowly increasing unique tag values.
Your query key is likely something you would want to put a tag on so you can do more things with that query key in influxdb queries. However that would constantly increase cardinality even further by a large amount given there are lots of queries (and likely faster because of code / query refactors).

So we are not really interested in statistics of single queries maintained by each app server pushing that data to influxdb, but instead rely on PostgresSQL slow query logs and/or pg_stat_statements.

In our app servers we only record metrics for a single tenant with a large database and all other tenants are merge together into the same "other tenants" metric. Reasoning is that if aggregated query stats look fine for a large database, they should also look fine for small databases (and slow queries are already handled at postgres level).

So app servers only collect more general things like query count per transaction, commit / rollback (count, rate, histogram on duration), commit / rollback timeout counts, query type (select, delete, ...) counts for a controlled set of tenants.

**Comment by rbygrave** [comment]
> So app servers only collect more general things

Ok interesting. I am definitely interested in SQL.

> When you calculate a key based on the query and its source code location then you generally have an endless amount of different keys over time

Well yes and actually I think I can fix this as I see it. More specifically I am very happy collecting metrics per unique SQL (this doesn't grow much - esp with Postgres due to array binding) but I do see the addition of location hurting the current design - that is a problem.  That is, combining sql and location (and name which is tightly correlated to location) into the hash is not the right thing to do longer term. What I should have done is separated the two and treated location as a dimension. People can still use MetaQueryMetric without the hash of course but the hash should not have combined sql + location.


#### An Example:

There is the exact same SQL query with 2 names (and locations).

name: orm.DOrderLine_OrderDao.findForUpdate_groups.lines           
loc: OrderDao.findForUpdate(OrderDao.java:38)           
sql:| select ...

name: orm.DOrderLine_OrderDao.findOrdersForPublishing_groups.lines 
loc:| OrderDao.findOrdersForPublishing(OrderDao.java:86)
sql:  select ..


If I look at name `orm.DOrderLine_OrderDao.findForUpdate_groups.lines` we see:
- It is fetching type `DOrderLine`
- It has an origin at `OrderDao.findForUpdate`
- And the underscore in `_groups.lines` tells me it is a secondary query 
- And `_groups.lines` tells us the relative path that invoked the query

So although I have one unique SQL query I might be interested in tuning the secondary query and I know where the origin of the query is in code etc.

To date, most of the time when we are looking at the query metrics for slow queries or expensive queries we mostly are looking at the metric names, locations and then afterwards look at the sql.

Now, that all said there is a problem with the design and the question is can I fix that and have my cake and eat it?  I think so.  Note that I am not putting these metrics directly into Influxdb, the metrics are ingested and then there is a 1 minute rollup (which handles the usual dimensions - server, environment etc) and then subsequent rollups 10min, 1hr, 1day.  So my challenge is to separate name and location into another dimension [separate from the actual sql].

**Comment by jnehlmeier** [comment]
> > So app servers only collect more general things
> 
> Ok interesting. I am definitely interested in SQL.

Yeah sure, that's cool. I am also interested in SQL but not in every SQL. Most SQL is fast, so I am not interested in those (especially with Ebean not having the n+1 lazy loading problem which could hide performance issues with lots of small/fast lazy fetch queries). 
Think about having 400 databases each having 400 entities and each entity has roughly 10 primary queries assigned to it. To some extend you would also rely on Ebeans good lazy loading, so you would need to add some secondary queries per entity.

So overall you might end up with roughly 5000 different queries. Do I really want to track them for 400 databases? Or do you I only want to track them for large databases? Do I really want to track all queries or am I only interested in queries that do not meet performance criteria? Tracking all queries for all databases also costs memory.

Thats why I prefer sticking to larger databases only and having performance criteria to check for. But yes postgres slow query logs and pg_stat_statement do not tell me which code produced the query. That is a nice feature of Ebean, but usually slow queries are complex and you usually find complex queries relatively easy in code. So I never really had problems finding the code that executed the slow query.

It would be great if Ebean would allow to configure metric collection only for a subset of tenants when in multi tenant mode.
Does your metric code account for different database sizes when using TenantMode.DB? What I mean is if metric collection is tied to the single multi-tenant Database instance or tied to the tenant id itself?

**Comment by rbygrave** [comment]
> not in every SQL

So for all non-bulk insert, update, delete Ebean internally tracks timing but not the actual SQL. What Ebean metrics does is differentiate between jdbc batch and non-batch insert, update, delete (we want to identify if there is a lot of non-batched insert update delete going on).

So actual SQL in terms of ebean metrics is select queries plus bulk insert, update delete statements.   


> 5000 different queries.

Over 17,000+ across multiple databases and multiple applications but typically we look at it per application (might be less than 200 distinct sql queries in an app).


> Tracking all queries for all databases also costs memory.

In terms of backend there is rollup of 1m, 10m, 1hr, 1day - and it only keeps a certain amount for each. We can't keep tones of 1min data but that is ok.


> So I never really had problems finding the code that executed the slow query.

Yes. We've also wanted to see the relatively fast queries that are hit a huge amount, plus the queries that have changed (were fast but now medium due to some data distribution changed with some bulk process).

A thought bouncing around is to put the "label" into the SQL as a comment. People could then label their queries if they have that desire and link sql database metrics back to code more easily.   


>  metric collection only for a subset of tenants when in multi tenant mode.

Ebean metric collection is _always on_ but tenant isn't part of it. Ebean internally has a "query plan" and timing metrics for queries are part of that. Ebean's timing metrics are LongAdder count, total, max (so not histograms and basically cheap - I have a pretty strong opinion on avoiding histograms, especially once we are collecting frequently enough. For example, my avaje metrics library uses basic timing (like what we have in ebean) or bucket timing - **not** histograms). 


> only interested in queries that do not meet performance criteria?

Well ultimately there could be a mechanism to automatically collect query plans based on performance criteria. Have the system look for the nuggets. That's part of the plan.


Note that ideally I get this to a point I can make it available to all ebean users who want to try it out. It could be a "proxy" that analyses and aggregates metrics to then publish them back or a full dashboard.

**Comment by rbygrave** [comment]
For this feature request we will go with added a `--micros(...)` with the time in micros.  Note that this time effectively includes the time to bind and execute returning the ResultSet (so unlike the ebean timing metrics in meta info that include processing the result / converting the result into beans).  This is especially important to note for findEach / findIterator queries.

Also worth noting that all timing in ebean is reported in micros unless otherwise stated. All the meta info timing metrics are in micros.
