### ISSUE TITLE
While setting up a database programmatically i get a "NoSuchFieldError: _objectFieldValueSeparatorWithSpaces"

### ISSUE THREAD

**Issue by scolastico** [ebean-orm/ebean#2271]
## Expected behavior
No exception is thrown.

## Actual behavior
Throws an exception with the following stack trace:
```console
java.lang.NoSuchFieldError: _objectFieldValueSeparatorWithSpaces
	at io.ebeaninternal.server.text.json.DJsonContext$Pretty.<init>(DJsonContext.java:62)
	at io.ebeaninternal.server.text.json.DJsonContext.<clinit>(DJsonContext.java:48)
	at io.ebeaninternal.server.core.InternalConfiguration.createJsonContext(InternalConfiguration.java:335)
	at io.ebeaninternal.server.core.DefaultServer.<init>(DefaultServer.java:234)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:112)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:35)
	at io.ebean.DatabaseFactory.createInternal(DatabaseFactory.java:130)
	at io.ebean.DatabaseFactory.create(DatabaseFactory.java:78)
	at me.scolastico.s.status.Application.main(Application.java:141)
```

### Steps to reproduce

I used this code inspired by the [documentation](https://ebean.io/docs/intro/configuration/#programmatic):

```java
      DataSourceConfig dataSourceConfig = new DataSourceConfig();
      if (config.getDatabaseType() == DatabaseType.SQLITE) {
        dataSourceConfig.setUrl("jdbc:sqlite:" + config.getSqliteFile());
        dataSourceConfig.setUsername("");
        dataSourceConfig.setPassword("");
        dataSourceConfig.setIsolationLevel(TxIsolation.READ_UNCOMMITTED.getLevel());
      } else {
        if (config.getDatabaseType() == DatabaseType.MYSQL) {
          dataSourceConfig.setUrl("jdbc:mysql://"
              + config.getMysqlHost() + ":"
              + config.getMysqlPort() + "/"
              + config.getMysqlDB()
          );
        } else {
          dataSourceConfig.setUrl("jdbc:mariadb://"
              + config.getMysqlHost() + ":"
              + config.getMysqlPort() + "/"
              + config.getMysqlDB() + "?useLegacyDatetimeCode=false"
          );
        }
        dataSourceConfig.setUsername(config.getMysqlUser());
        dataSourceConfig.setPassword(config.getMysqlPass());
      }
      DatabaseConfig dbConfig = new DatabaseConfig();
      dbConfig.setDataSourceConfig(dataSourceConfig);
      dbConfig.setRunMigration(config.isEnableDatabaseMigrations());
      database = DatabaseFactory.create(dbConfig); // Application.java:141
```

I try'd it with a MySQL and a SqLite connection but both run into the same error.

**Comment by rbygrave** [comment]
> java.lang.NoSuchFieldError

NoSuchFieldError pretty much implies that we have code that is expecting a version of a jar/dependency (with a field) but there is a different version of the jar/dependency in the classpath.  So we see this as a NoSuchFieldError.

> _objectFieldValueSeparatorWithSpaces

This is the field that the code expects is there but isn't.

> at io.ebeaninternal.server.text.json.DJsonContext$Pretty.<init>(DJsonContext.java:62)

DJsonContext line 62 is the code we want to look at ... so we go there and see what it's doing.

```java
  private static class Pretty extends DefaultPrettyPrinter {
    Pretty() {
      _objectFieldValueSeparatorWithSpaces = ": ";
    }
  }
```
line 62 is:
```java
      _objectFieldValueSeparatorWithSpaces = ": ";
```
Now we see `class Pretty extends DefaultPrettyPrinter` ... and `DefaultPrettyPrinter` is `com.fasterxml.jackson.core.util.DefaultPrettyPrinter` ... which is a class from Jackson.

That is, Pretty is extending a Jackson class `com.fasterxml.jackson.core.util.DefaultPrettyPrinter`.  It expects `DefaultPrettyPrinter` to have a field called `_objectFieldValueSeparatorWithSpaces`

... BUT at runtime we see NoSuchFieldError indicating the the `com.fasterxml.jackson.core.util.DefaultPrettyPrinter` that is in the classpath does NOT have this field.

The Ebean Pretty code is depending of a version of Jackson DefaultPrettyPrinter that has that field but the version of Jackson DefaultPrettyPrinter in the classpath does NOT have that field.

We need to compare the versions of the Jackson dependency. Specifically DefaultPrettyPrinter is in jackson-core and we need to compare the version of the jackson-core jar (version of jackson-core in the classpath vs version of jackson-core used to compile Ebean).  We are wondering if the version of the jackson-core jar in the classpath is very old or very new (why does it not have the `_objectFieldValueSeparatorWithSpaces` field.

Looking at the Jackson code we see `_objectFieldValueSeparatorWithSpaces` should be from verison 2.9 onwards so we start to suspect the version of jackson-core in the classpath is less than version 2.9.

----
Looking at the Ebean code we kind of are asking, why did we subclass DefaultPrettyPrinter rather than create it and mutate it's separator options.  Yeah well ... we got slightly nicer pretty print output by avoiding extra whitespace that otherwise we can't avoid with the separators - kind of marginal decision - hmmm.

----

Q: What is the version of jackson-core in the classpath?  Is it older than 2.9?  If so can you bump up to a later version of jackson-core (ideally latest is safest wrt vulnerabilities in jackson).

**Comment by rbygrave** [comment]
Note: The Jackson code that meant we extended DefaultPrettyPrinter and set the field was:
```java
        _objectFieldValueSeparatorWithSpaces = " " + separators.getObjectFieldValueSeparator() + " ";
```
... as this code always puts in a leading space regardless (and at some that was not deemed 'pretty enough').

An alternative approach that looks like it would get the same result would be to instead override the writeObjectFieldValueSeparator() method.

**Comment by scolastico** [comment]
Yeah then i think i found the issue in one of the other dependency's (org.springframework.boot):
![image](https://user-images.githubusercontent.com/26954501/126757683-01ac77b7-fdf9-4c90-970f-6307b169bd6c.png)

**Comment by scolastico** [comment]
I solved the problem by forcing maven to use a newer version:

```xml
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
      <version>2.12.4</version>
    </dependency>
```

Many thanks for your help. <3
