### ISSUE TITLE
ServiceLoader can't find a SpiContainerFactory

### ISSUE THREAD

**Issue by CollinAlpert** [ebean-orm/ebean#2286]
I am currently writing a custom user provider for Keycloak and decided to use Ebean to query my database of users. I don't know if it's the way the JAR file is packed (I am using the Maven Assembly plugin) or what it is, but whenever I make any query to the database using Ebean, I get the exception `IllegalStateException: Service loader didn't find a SpiContainerFactory?`
The exception is thrown in DatabaseFactory.java:162. I am using v12.10.0.

## Expected behavior
I can query the database and expect results.

## Actual behavior
The described exception occurs.

### Steps to reproduce
Write a simple SPI for Keycloak, build a JAR with dependencies and copy it into the standalone/deployments folder of Keycloak.

**Comment by jnehlmeier** [comment]
Are you sure that you have ebean-core in your classpath? This can happen if you only have ebean-api but not ebean-core.

**Comment by CollinAlpert** [comment]
I have the dependencies ebean, ebean-api and ebean-core in my classpath. Unfortunately the error still persists.

**Comment by rbygrave** [comment]
So that suggests something interesting with respect to the classpath or classloader?  

The implementation of `SpiContainerFactory` is `io.ebeaninternal.server.DContainerFactory` that exists in ebean-core.  So can you check that you have access to that class in the classpath?

Noting that the way ServiceLoader works is that the resource META-INF/services/io.ebean.service.SpiContainerFactory is loaded and that resource contains the implementation class which is `io.ebeaninternal.server.DContainerFactory` ... so is it the case that the **Maven Assembly plugin** is messing with that resource file?

**Comment by CollinAlpert** [comment]
That could actually be, is there anything special I should have in the plugin's configuration?

**Comment by CollinAlpert** [comment]
So I just checked and both the class file DContainerFactory as well as the file META-INF/services/io.ebean.service.SpiContainerFactor exist in the resulting JAR, so they should be accessible.

**Comment by rbygrave** [comment]
Hi @CollinAlpert , how are you going with this issue?  I think it isn't so much a ebean issue but more a classpath issue / assembly plugin issue?

**Comment by CollinAlpert** [comment]
To be honest I just used another ORM for this specific project. I don't really know what to do in regard to the assembly plugin, as in what configuration to try, since it would just be plain trial and error. Feel free to close this issue if you think nothing can/should be done on the ebean side.

**Comment by rbygrave** [comment]
Yeah, we'd need a failing test case to look at. 

I'll close this, if someone provides a failing test case then we can re-open and look at it.
