### ISSUE TITLE
Groovy test classes with Spock cause NPE with Query beans

### ISSUE THREAD

**Issue by rvowles** [ebean-orm/ebean#2292]
## Expected behavior

The Query bean would operate as it does in the Kotlin or Java code 

## Actual behavior

When using a Query bean in Spock (not sure about plain old Groovy tests) only the query beans cause an NPE. I can create and save normally, I can use the database object normally, but the QueryBean wille explode. 

### Steps to reproduce

Full worked example is here: https://github.com/rvowles/exploding-spock-ebean

If you clone it and do a `mvn clean test` it will work, if you then swap the lines:

so the query bean are used instead of the database line:

```
    // this line NPEs
        new QDbSample().name.eq("fred").findCount() == 1
    //   this line works
//        database.find(DbSample).where().eq("name", "fred").findCount() == 1
```

It explodes with an NPE:

```
new QDbSample().name.eq("fred").findCount() == 1
|               |    |
|               null java.lang.NullPointerException: Cannot invoke method eq() on null object
|                       at org.example.SampleSpec.i save a new record(SampleSpec.groovy:16)
<
```

I'm not sure if it is solvable or its something weird Groovy is doing, but I thought I would log it as an issue. If it is something weird, it would probably just be worth a note to indicate that you can't use Query beans with Spock. 

You can load it into IDEA as well and have your merry way with it :-)

**Comment by rbygrave** [comment]
Cool, I'll have a look :)

**Comment by rbygrave** [comment]
So the interesting part of the compiled groovy looks like:

```
SpockRuntime.verifyCondition($spock_errorCollector, $spock_valueRecorder.reset(), "new QDbSample().name.eq(\"fred\").findCount() == 1", Integer.valueOf(16),...
```
and specifically the query bean query is defined as a String - `"new QDbSample().name.eq(\"fred\").findCount() == 1"`

So ebean-agent is not seeing the query bean `.name` field access and changing it as we need it to because is just a string and not `GETFIELD` bytecode.

One option is to change the query to use `_name()` [_method_] rather than `name` [_field_]:
```groovy
new QDbSample()._name().eq("fred").findCount() == 1
```
What this is doing is manually making the change that the ebean-agent makes to "code that uses query beans". That is, with query beans ebean is somewhat "simulating field access as property access". It does 2 things:
- Adds those underscore methods to query beans themselves for each "property"
- For calling code changes the GETFIELD calls to instead call those underscore methods

What we are doing with manually changing to use `_name()` is doing that second part of the enhancement ourselves.

Now, is there a better solution?  Hmmm.  


### Note: kotin query beans

Noting that for Kotlin query beans (query beans generated as kotlin source code rather than java source code) we don't need the second enhancement. That is, with kotlin query beans because kotlin has "properties" we use kotlin properties rather than java fields and this means we only need to enhance the kotlin query beans themselves and not the calling code.


### Note: `mvn clean process-test-classes`

Side note: Running `mvn clean process-test-classes` will show us what ebean-agent is going to enhance (in src/main and src/test). So that is handy to know.  We can run that and then look at the query bean .class files geting intellij to decompile them.

We see the underscore methods that ebean-agent added to the query bean.

```java

  // IntelliJ API Decompiler stub source generated from a class file
  // Implementation of methods is not available

package org.example.models.query;

@io.ebean.typequery.Generated("io.ebean.querybean.generator")
@io.ebean.typequery.TypeQueryBean("v1")
@io.ebean.typequery.AlreadyEnhancedMarker
public class QDbSample extends io.ebean.typequery.TQRootBean<org.example.models.DbSample,org.example.models.query.QDbSample> {
    private static final org.example.models.query.QDbSample _alias;
    public io.ebean.typequery.PUuid<org.example.models.query.QDbSample> id;
    public io.ebean.typequery.PString<org.example.models.query.QDbSample> name;

    public static org.example.models.query.QDbSample alias() { /* compiled code */ }

    public static org.example.models.query.QDbSample forFetchGroup() { /* compiled code */ }

    public QDbSample() { /* compiled code */ }

    public QDbSample(io.ebean.Transaction transaction) { /* compiled code */ }

    public QDbSample(io.ebean.Database database) { /* compiled code */ }

    private QDbSample(boolean alias) { /* compiled code */ }

    private QDbSample(io.ebean.Query<org.example.models.DbSample> fetchGroupQuery) { /* compiled code */ }

    public io.ebean.typequery.PUuid<org.example.models.query.QDbSample> _id() { /* compiled code */ }

    public io.ebean.typequery.PString<org.example.models.query.QDbSample> _name() { /* compiled code */ }

    public static class Alias {
        public static io.ebean.typequery.PUuid<org.example.models.query.QDbSample> id;
        public static io.ebean.typequery.PString<org.example.models.query.QDbSample> name;

        public Alias() { /* compiled code */ }
    }
}
```

**Comment by rbygrave** [comment]
We can use a local `@CompileStatic` helper method like:

```groovy
  @CompileStatic
  static def findCount2(String name) {
    return new QDbSample().name.eq(name).findCount()
  }
```
```groovy
    then:
    // this line NPEs
        findCount2('fred') == 1
        new QDbSample()._name().eq("fred").findCount() == 1
```

**Comment by rvowles** [comment]
Well I think that solves it and its a good example for the issue history, so lets close it? Thanks for your help!

**Comment by rbygrave** [comment]
Yeah cool.  I'll update the documentation and then close this one.
