### ISSUE TITLE
SQL for Index and Foreign Key didn't get generated if I map ID column after @ManyToOne 

### ISSUE THREAD

**Issue by almothafar** [ebean-orm/ebean#2415]
This issue is kinda strange with an easy workaround to fix it, I'm not sure if that's an issue though, so the idea is if I have Model that maps another Model and used @JoinColumn to do that mapping (I'm not sure if this is part of issue actually), the SQL script that should be generated only appears if and only if mapping the id column is BEFORE the mapping it with @ManyToOne 

I mean this is confusing but here is an example:

### Steps to reproduce

If I have UserSubscriptions bean, that bean got Topic, like the following:

```java
@Entity
@Table(name = "UserSubscription", schema = "alerts")
public class UserSubscription extends Model {
    @ManyToOne(optional = false, cascade = {CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH})
    @DbForeignKey(onDelete = ConstraintMode.CASCADE)
    @JoinColumn(name = "TopicId")
    private Topic topic;

    @Column(name = "TopicId", nullable = false, insertable = false, updatable = false)
    private Integer topicId;
```

SQL should generate:

```sql
create index [ix_UserSubscription_TopicId] on [alerts].[UserSubscription] ([TopicId]);
alter table [alerts].[UserSubscription] add constraint [fk_UserSubscription_TopicId] foreign key ([TopicId]) references [alerts].[Topic] ([Id]) on delete cascade;

```

But in this case, here it is not working, I have to maintain the order between properties so I have to change my code to:

```java
@Entity
@Table(name = "UserSubscription", schema = "alerts")
public class UserSubscription extends Model {

    @Column(name = "TopicId", nullable = false, insertable = false, updatable = false)
    private Integer topicId;

    @ManyToOne(optional = false, cascade = {CascadeType.MERGE, CascadeType.PERSIST, CascadeType.REFRESH})
    @DbForeignKey(onDelete = ConstraintMode.CASCADE)
    @JoinColumn(name = "TopicId")
    private Topic topic;
```

In this case, the SQL script showing up.

**Comment by rbygrave** [comment]
Why are we mapping the `TopicId` column twice?  Why is it mapped to a `@Column` as well as a `@ManyToOne` ?  

That is, why is the extra `@Column(..) Integer topicId;` there at all? (We would generally only expect the `@ManyToOne`)

**Comment by almothafar** [comment]
I have a specific scenario for this, where I need id without triggering lazy load with `getTopic`.

Anyways, I don't think it is a major issue but I just want to record this, if you think this is not worth working on you can close it.

**Comment by jnehlmeier** [comment]
In JPA/EclipseLink I used something like that before. Using the above classes as example I think it was along the lines of having a larger list of `UserSubscription` instances and instead of triggering lazy load by calling `getTopic()` I collected `topicId`s and did a query manually. This was a last resort solution  to avoid lots of lazy load queries when `JOIN FETCH` and `BATCH FETCH` both did not work properly in JPA/EclipseLink.

Sometimes I also used it to optimize a query since EclipseLink usually uses the pattern `JOIN subscription.topic t WHERE t.id = :id` instead of just `WHERE subscription.topicId = :id`. So it favors adding a `JOIN` and  comparing the primary key column instead of comparing the foreign key column directly. That extra `JOIN` sometimes caused slow query plans in the DB.

So it is mainly used as a workaround for other issues.

**Comment by rbygrave** [comment]
*> where I need id without triggering lazy load with getTopic.*

Ebean will *NOT* invoke lazy loading for this case.
- getTopic() ... should *not* invoke lazy loading with Ebean
- getTopic().getId() ... similarly should *not* invoke lazy loading with
Ebean.

It is not until we fetch some other non-Id property of Topic that lazy
loading will be invoked.  That is, Ebean specifically knows not to invoke
lazy loading for this case (given we have selected/loaded the foreign key
column) and yes I believe this is somewhat unlike Hibernate (and wasn't
sure about Eclipselink) where this indeed can invoke lazy loading.

That is, people maybe do this because they have needed to in the past with
Hibernate and Eclipselink but this should not be the case for Ebean.  We do
not need to "mirror" a foreign key column as a scalar property to avoid
lazy loading - it's not something we need to do when we are using Ebean.


*> That extra JOIN sometimes caused slow query plans in the DB.*

We need to be careful around the case of OneToOne (specifically the side
that acts like a OneToMany) ... but this is a ManyToOne and no JoinTable so
we should have no problems controlling the existence of the sql join to
topic here.  This should not be the case of getting an unexpected join.


Cheers, Rob.

**Comment by rbygrave** [comment]
Pushed a fix, again noting that really people shouldn't need to map the same column twice.
