### ISSUE TITLE
@ElementCollection is not queried in entity using Finder.query

### ISSUE THREAD

**Issue by SchlauFuchs** [ebean-orm/ebean#2431]
## Expected behavior
Entity queried should have ElementCollection annotated properties populated

## Actual behavior
properties are null

### Steps to reproduce
I have this entity class (slightly reduced from our codebase):

```kotlin
@Table(name = "user")
@Entity
data class User(
    @Id
    val id: String,
    val title: String,
    val givenNames: String,
    val surname: String,
    val emailAddress: String,
    val preferredName: String,
    val corporateName: String,
    val loginType: UserLoginType, // an enum
    val login: String,
    val status: UserStatusCode, // also an enum
    val lockedOut: String,

    @Column(name = "office")
    val officeCode: String,

    val cusAccountRef: String,

    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(
        name = "type_of_user",
        joinColumns = [JoinColumn(name = "usr_id")]
    )
    @Column(name = "type")
    val roles: SortedSet<String>,

    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(
        name = "user_profile",
        joinColumns = [JoinColumn(name = "usr_id")]
    )
    @Column(name = "prf_id")
    val profiles: SortedSet<String>,

    @OneToMany(mappedBy = "user")
    private val firmRelationships: List<FirmUser>,

    @OneToOne
    @JoinColumn(name = "id", nullable = true)
    val userLastLogin: UserLastLogin?,
) {
    companion object Find : Finder<String, User>(User::class.java)
}
```

The find method is executed like this:
```kotlin
        return User.query()
            .fetch("userLastLogin")
            .fetchQuery("firmRelationships")
            .fetch("firmRelationships.firm")
            .fetch("roles")
            .fetch("profiles")
            .where().idEq(userId)
            .findOne()!!
```

at unit test time two queries are executed:

```console
txn[1002] select t0.id, t0.title, t0.given_names, t0.surname, t0.email_address, t0.preferred_name, t0.corporate_name, t0.login_type, t0.login, t0.status, t0.locked_out, t0.off_code, t0.cus_account_ref, t3.usr_id, t3.prior_login from user t0 left join user_last_login t3 on t3.usr_id = t0.id where t0.id = ?; --bind([edited], ) --micros(567039)
txn[1002] select t0.usr_id_user, t0.associated, t0.usr_id_user, t1.id, t1.corporate_name, t1.status from firm_user t0 join user t1 on t1.id = t0.usr_id_firm where (t0.usr_id_user) in (?); --bind(Array[1]={[edited]}) --micros(177506)
```
The first is the root query, the second one is to populate `firmRelationships`
No query for `roles` or `profiles` is executed. The returned entity has those properties set to null.

This problem is occuring in JDK 11 with ebeans 12.12.3 (also tested with 12.12.2)

**Comment by SchlauFuchs** [comment]
While debugging and trying to simplify my code, I tried to remove the `UserLastLogin` entity and its relationship above and substitute it with a @SecondaryTable property instead:

```kotlin
@Table(name = "user")
@SecondaryTable(name = "user_last_login", pkJoinColumns = [PrimaryKeyJoinColumn(name = "usr_id")])
@Entity
class User(
[....]
    @Column(name = "prior_login", table = "user_last_login")
    val lastLogin: OffsetDateTime?
```

This now triggers an NPE at runtime which I could inspect a little in my IDE:
![image](https://user-images.githubusercontent.com/962205/139754805-7dbb08a2-569f-4af3-abe7-57b07a16dc51.png)
The TableJoin table property for the `roles` collection is null and the comparison in line 897 fails.

Something here took a completely wrong direction.

**Comment by rbygrave** [comment]
The next step is to distill a failing test case (ideally as a PR). I do note that the code is looking to use `SortedSet<String>` rather than `Set<String>` which isn't correct per say - not sure if that is material.

**Comment by SchlauFuchs** [comment]
Hi, thanks for looking into it. I have not heard that SortedSet is
unsupported. In JPA this should work as long as the type of the collection
is *Comparable*

I have circumvented the problem with some ugly code now, I have to see when
I have some time for contribution.

**Comment by rbygrave** [comment]
*> JPA this should work as long as the type of the collectionis
*Comparable**

I don't see that in the JPA spec. Can you point me to where this is
referenced?

What we can see in section 2.2 is:

Collection-valued persistent fields and properties must be defined in terms
of one of the following col-
lection-valued interfaces regardless of whether the entity class otherwise
adheres to the JavaBeans
method conventions noted above and whether field or property access is
used:
*java.util.Collec-tion, java.util.Set, java.util.List[3], java.util.Map*.




*> SortedSet *

It looks to me like Hibernate supports SortedSet. This is the potential
source of the issue being hit here, if you get a chance you could change
that to Set to see if that still reproduces.  I hadn't got around to
reproducing yet.



Cheers, Rob.

**Comment by rbygrave** [comment]
Reviewing the tests and code and SortedSet isn't going to work. It isn't treated as a "ToMany property" so doesn't get seen as an `@ElementCollection`.

Messing with:
https://github.com/ebean-orm/ebean/blob/master/ebean-test/src/test/java/org/tests/model/elementcollection/EcsPerson.java
https://github.com/ebean-orm/ebean/blob/master/ebean-test/src/test/java/org/tests/model/elementcollection/TestElementCollectionBasicSet.java

... and making it a SortedSet and it just does not get far.


So are you able to make those `java.util.Set` instead of `SortedSet`?  That should then work as expected.  

Cheers, Rob.

**Comment by rbygrave** [comment]
I'll close this now, with the assumption this was sorted by changing to using `java.util.Set`

**Comment by SchlauFuchs** [comment]
It was solved by using an @Formula and a helper function.
