### ISSUE TITLE
SQL Update doesn't handle named parameters for array types in Postgres

### ISSUE THREAD

**Issue by majkiw** [ebean-orm/ebean#2436]
## Expected behavior
When an underlying table contains a `text[]` or `character varying[]` and we use `.sqlUpdate` the parameter should be passed to SQL in the correct format, so that it is inserted/updated.

## Actual behavior
It works for positional parameters, but for named parameters it is passed to JDBC as `"a,b"` instead of `"{a,b}"`.

### Steps to reproduce
See test TestDbArray_basic#sqlUpdate_withArray  in:
https://github.com/ebean-orm/ebean/pull/2434

**Comment by rbygrave** [comment]
Right so there is something interesting to note here. The reason why it works for positioned parameters and not named parameters is because with named parameters Ebean can't be sure if we are wanting "bind parameter expansion" or "array binding"

For example

```java
 
    // Here we want "Postgres ARRAY binding"
    DB.sqlUpdate("UPDATE earray_bean SET phone_numbers = :pns")
      .setParameter("pns", List.of("4321", "9823"))
      .execute();

   // Here we want "bind parameter expansion" ...
    DB.sqlUpdate("UPDATE earray_bean SET active = true where id in (:ids)")
      .setParameter("ids", List.of(42,43))
      .execute();

```

With positioned parameters Ebean knows that if we are binding a collection it MUST be array binding. With named parameters it can't tell that (unless it parsed the sql and it doesn't do that).

So the "Fix" for this issue is to allow us to explicitly use array binding with DtoQuery and SqlUpdate using a new `setArrayParameter()` method.  The above then becomes.

```java
 
    DB.sqlUpdate("UPDATE earray_bean SET phone_numbers = :pns")
      .setArrayParameter("pns", List.of("4321", "9823"))   // Explicitly saying we want Array binding
      .execute();

```

**Comment by majkiw** [comment]
That's a great workaround. Thank you.
