### ISSUE TITLE
DB2: select distinct with lob/clob fields

### ISSUE THREAD

**Issue by NSzemenyei** [ebean-orm/ebean#2495]
## Actual behavior

If a query needs ```distinct``` in a select clause (e.g. join many tables) and a lob/clob field is also in the select, DB2 throws an SQL Exception ```SQLCODE=-134, SQLSTATE=42907,```, cause: https://www.sqlerror.de/db2_sql_error_-134_sqlstate_42907.html 

@rPraml and I implemented a possible solution in our fork: https://github.com/FOCONIS/ebean/pull/55 . 
Our idea is to exclude the lob/clob properties from the ```select distinct``` clauses. These props have to be loaded lazy.
We assume, the same fix would be also good for Oracle,

### Steps to reproduce
Execute the test without the fixes in https://github.com/FOCONIS/ebean/pull/55

@rbygrave can you please check this issue and give us feedback?

**Comment by rbygrave** [comment]
So yes I see the fix approach - it might be what we want.  The problem for me is that I see it highlight an issue where ideally we want the SqlTreeNode things to be immutable. Looking at SqlTreeNode etc it really doesn't 2 things which is:
A) build the sql  
B) read the query result / ResultSet.

Really what I desire is that whatever is doing B) is more strictly immutable and probably minimal as it is held/cached by the CQueryPlan (which currently holds SqlTree).

So, the PR looks ok but it makes SqlTreeNode more mutable (removes some finals) and that might be ok but what I think I need to do is extract the B) functionality from SqlTree/SqlTreeNode into something else which is strictly immutable and minimal ... and then confirm that this PR is fine there (we can have mutating SqlTreeNode while we do A) and don't care because it is short lived).

**Comment by rbygrave** [comment]
The original PR approach planned that modified the SqlTreeNode should be all good.

That is, I have made my change I was looking to do so now we have `SqlTreeLoad things` and these are fully immutable (created from the associated SqlTreeNode things). Internally the SqlTreeNode things are now only used temporarily to build the SQL and build the SqlTreeLoad things and as such it is fine for the SqlTreeNode things to mutate.
