### ISSUE TITLE
@OneToOne with @History produces incorrect query

### ISSUE THREAD

**Issue by tobias-** [ebean-orm/ebean#2652]
## Expected behavior

Getting a reference to the bean.

## Actual behavior

SQLException because Ebean produces an invalid query

### Steps to reproduce

PR #2651 has a testcase asserting working behaviour.

Ebean produces an invalid query when trying to lazy load @OneToOne
from a historical bean. This test asserts working behaviour.

The actual error (at least for postgresql) is:

Persistence Query threw SQLException:Parameter "`#2`" is not set; SQL statement:
```sql
select t0.id, t0.name, t0.version, t0.when_created, t0.when_modified, t1.id from historyless_one_to_one t0 
left join history_one_to_one_with_history t1 on t1.historyless_one_to_one_id = t0.id and
(t1.sys_period_start <= ? and (t1.sys_period_end is null or t1.sys_period_end > ?))
 where t0.id = ?
```

The bind values:
```
[90012-212] Bind values:[1, ]
```

As a side-note, I'm confused why the bean is lazy-loaded, as it's a `@OneToOne` which defaults to eager, and therefore should've been loaded together with the history bean?

**Comment by rbygrave** [comment]
The underlying issue is that Ebean internally needs to keep a count of the number of times AS OF predicates are added for joins and it wasn't doing that well - the PR fixes that and DbSqlContext "owns" that counter for all the JOIN AS OF cases.

For the test I've modified it to have 4 queries, 2 for the history -> less history path and 2 for the other direction.  For each direction there is the lazy loading option and the fetch eager option.

> @OneToOne which defaults to eager,

First note that my general thinking is that the `@OneToOne(mappedBy=...)` side should be FetchType.LAZY or otherwise it requires a JOIN to the other side to obtain the foreign key.  As I see it, my recommendation is that the `@OneToOne(mappedBy=...)` side should always be FetchType.LAZY for that reason.


> @OneToOne which defaults to eager ... why the bean is lazy-loaded

So EAGER here **_for Ebean_** in the ManyToOne and OneToOne means by default include this property in the `select` which translates to fetch the foreign key value.  On the side that owns the foreign key column that just means include the foreign key value - no big deal / trivial.  However, for OneToOne **_on the mapped by side_** / the non-owning side ... EAGER here means join back to the other side of the OneToOne to fetch the foreign key value only - so it needs to add the join back to the other table for this.

The background of problem here is that JPA EAGER/LAZY would be better from an Ebean perspective if there was additionally a DEFAULT option but there isn't. As I see it, the problematic case is this "non-owning side of a OneToOne" and this is where we could perhaps reasonably expect that Ebean would fetch [all the default eager fetch properties] of the other side rather than **_only_** the foreign key column(s) - with the thinking that it has to join to the other table, so why not fetch those properties while it's at it? 

If we use Ebean FetchGroup - https://ebean.io/docs/query/fetchgroup ... then of course default EAGER/LAZY etc does not matter and we can choose exactly what the projection is.  

I believe this  "non-owning side of a OneToOne" is confusing for even experienced people. 

----
Perhaps have a look at the changes I've made to the test with those 4 different queries and see what you think. Maybe re-state which case is not really behaving as expected and we can look closely at it.

**Comment by tobias-** [comment]
> > @OnetoOne which defaults to eager,
> 
> First note that my general thinking is that the `@OneToOne(mappedBy=...)` side should be FetchType.LAZY or otherwise it requires a JOIN to the other side to obtain the foreign key. As I see it, my recommendation is that the `@OneToOne(mappedBy=...)` side should always be FetchType.LAZY for that reason.

Interesting. I've always considered joins on id a non-issue, and just the cartesian product and the number of queries the only real enemies, thus keeping EAGER on all `@XXXToOne` mappings. I can definitely see cases where it would matter though, but I've considered it the archetype of premature optimization as just starting to fetch a new property for any reason leads to more queries.

> > @OnetoOne which defaults to eager ... why the bean is lazy-loaded
> So EAGER here **_for Ebean_** in the ManyToOne and OneToOne means by default include this property in the `select` which translates to fetch the foreign key value. On the side that owns the foreign key column that just means include the foreign key value - no big deal / trivial. However, for OneToOne **_on the mapped by side_** / the non-owning side ... EAGER here means join back to the other side of the OneToOne to fetch the foreign key value only - so it needs to add the join back to the other table for this.

Agreed that it would make sense to allow the ORM-layer to handle it the way it thinks best with the option to explicitly override it.

> The background of problem here is that JPA EAGER/LAZY would be better from an Ebean perspective if there was additionally a DEFAULT option but there isn't. As I see it, the problematic case is this "non-owning side of a OneToOne" and this is where we could perhaps reasonably expect that Ebean would fetch [all the default eager fetch properties] of the other side rather than **_only_** the foreign key column(s) - with the thinking that it has to join to the other table, so why not fetch those properties while it's at it?

That was my thinking and what led to my question, yes.

> If we use Ebean FetchGroup - https://ebean.io/docs/query/fetchgroup ... then of course default EAGER/LAZY etc does not matter and we can choose exactly what the projection is.

This is something I haven't seen before. We don't often use `.select()` / `.fetch()`, but it seems a much more refactoring-safe way of doing it. If we can use this to control what to fetch (e.g. fetch the owning side) when we retrieve the historical (non-owning) bean, it should allow for more optimized queries..

> I believe this "non-owning side of a OneToOne" is confusing for even experienced people.
> 
Yes I agree. YES! (And I'm not that experienced).


> Perhaps have a look at the changes I've made to the test with those 4 different queries and see what you think. Maybe re-state which case is not really behaving as expected and we can look closely at it.

The problem we had was fetching a historied object and then doing `historied.getNonHistoriedBean().getNameProperty()`. I ran a test with a slightly modified test case (just added getName() and asserted that it was correct) which worked well now (failed before), so I believe this fixes all our problems. The test cases you made perfectly mirror the problems we had (except for the `getId()` instead of `getNameProperty()`), but since I confirmed that case as well, everything seems correct.

We will have to check all the mappedBy and make sure they're `LAZY`, so thanks for clarifying that.

Thanks for quick fix and thorough explanation!

**Comment by rbygrave** [comment]
> I've always considered joins on id a non-issue

Well, that is going to be true enough a lot of the time. I'm naturally on the more conservative side wrt SQL etc. What I'd say is:
- _that join isn't free_ 
- plus the application didn't _explicitly request_ that join 
- plus frequently as app devs we only find out the "real cost" in production


> getNameProperty()

Yeah, I could add that to those test asserts making them closer to the more realistic case.

Cool, I'll adjust those tests and close this and look to release as 13.3.1.
