### ISSUE TITLE
Q: Should we add `findOneOrThrow()` as syntactic sugar for `.findOneOrEmpty().orElseThrow(..)`

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#2707]
Q: Should we add `findOneOrThrow()` as syntactic sugar for `.findOneOrEmpty().orElseThrow(..)`
```java
.findOneOrThrow()
```

```java
// as syntactic sugar for 
.findOneOrEmpty()
.orElseThrow(() -> new EntityNotFoundException("<entity type> not found for " + id));
```

----
**Background:**
- find & findOne return a `@Nullable`
- findOneOrEmpty returns a `Optional<T>`

If we hit the scenario **_often enough_** that we want to throw an exception when "finding one entity doesn't find anything" ... then this syntactic sugar might be quite good to add.

If we did add this it's likely that we also want the option of a `Supplier<T extends Throwable>` just like `Optional` does. 

So we'd add:

- `findOneOrThrow()`    ... throws a EntityNotFoundException with a good message
- `findOneOrThrow(Supplier<T extends Throwable>)`    ... supplier of the throwable

Do we hit this often enough that we should add this syntactic sugar `.findOneOrThrow()` ?

**Comment by jnehlmeier** [comment]
Hm, in a large code base there are only two cases I wanted to throw exception when data isn't found in database:

1.) The data is something I have inserted by hand via sql scripts. This is usually some base data used by the app, that is never created by the app user. It must exist, otherwise the app would not function properly. However in that case checking for `null` and throwing `IllegalStateException` might be more appropriate. I don't need to construct an optional because that situation should never happen, as it is a broken deployment of the app.
2.) When a client makes a server call and the server code needs to load something **by id**. In that case I know that the client UI is outdated because someone else has deleted the requested entity. By throwing a descriptive, app specific exception I can tell the client which data hasn't been found and the client can reload UI sections.

In all other cases I usually return `Optional.empty` (or `null` in legacy code) because the query has some where condition that is valid to not match anything.

So for now I wasn't in the need for `findOneOrThrow` unless I would do the "find by id" thing in a more specific way via query beans instead of the Database.find() method (e.g. to apply some lazy fetching).

I usually have an abstract base dao / finder with
```java
Optional<T> findById(Long id) // used by code that wants to load something and then delete it (JPA style). Things that are already gone are fine, so the code would skip deletion on `Optional.empty` and would not fail.
T findByIdOrThrow(Long id) throws OutdatedDataException
T findByIdOrThrow(Long id, Reason reason) throws OutdatedDataException
```
which are implemented using `Database.find()` and can be overridden if needed.

But for developers who do not use `Database.find()` and do as much as possible with query beans, the syntactic sugar could be useful. In that case I would always stick to `findOneOrThrow(Supplier<T extends Throwable>)` because I would need to convert `EntityNotFoundException` with an english only error message to something more meaningful anyways.

**Comment by rbygrave** [comment]
Great comments. Maybe leads to some other questions:
- Should we i18n error messages that have some reasonable chance of getting to users?  Or even better, all messages?
- Should we add `findByIdOrThrow()` to `io.ebean.BeanFinder` (with `BeanRepository` extending `BeanFinder`) ?
- Lack of a good exemplar app using "repository"

**Comment by jnehlmeier** [comment]
> Great comments. Maybe leads to some other questions:
> 
> * Should we i18n error messages that have some reasonable chance of getting to users?  Or even better, all messages?

Usually exception messages of libraries are pretty specific, have a technical language and contain information the user has no idea about. It is very rare you want to pass them through to the user. So I don't think it is worth the effort. On the other hand, there are developers who do not speak English very well. Might be helpful to see the error message in their mother language.

> * Should we add `findByIdOrThrow()` to `io.ebean.BeanFinder` (noting that `BeanRepository` extends `BeanFinder`) ?

I tend to say no. Imagine you have:
1. `CustomerFinder.findByIdOrThrow()`: Throws `EntityNotFoundException` with a technical error message because as a library you don't want to hide information. So it could be something like "Entity of type xyz with id x not found in database y".
2. `CustomerFinder.findByIdOrThrow(Supplier<Throwable> s)`: Now you can use your own exception, however calling that method is always pretty long, e.g. `findByIdOrThrow(id, () -> new CustomNotFoundException(someOptionalExtraInfo))`.
3. Now you want your custom `findByIdOrThrow` method, so you don't have the code calls of 2. scattered around in your code base. Maybe you also want your custom exception to be a checked exception instead of a runtime exception.

So as soon as you end up in 3. the Ebean provided methods become a burden. First you need a name that does not clash with the Ebean provided method names and second you usually don't want that Ebean provided public findById API anymore  because you now have your custom version.

I guess I would wait to see if more people want that syntactic sugar out of the box.

> * Lack of a good exemplar app using "repository"

Hehe, didn't even know that `BeanFinder` and `BeanRepository` exist. In a small app I used `Finder` directly. But in a larger app I don't use any of these anyways (trying to hide Ebean as much as possible and don't like the public finder API giving access to db/query which mislead developers to write queries outside the finder implementation)

**Comment by rbygrave** [comment]
> wait to see if more people want that syntactic sugar out of the box

Yes, lets go with that.

> don't like the public finder API giving access to db/query which mislead developers to write queries outside the finder implementation

Noting that `abstract BeanFinder` kind of did the right thing and made those methods protected only (not public).

Finder could similarly have been made abstract with those methods as protected only (not public). It's subtly different from BeanFinder in that it uses "late access" to the underlying database instance making it friendly to be used as static field on entity classes.  BeanFinder really is designed for DI injection.

If I remember correctly, Finder made it's way into ebean from play-ebean and was used a lot in that concrete (non extending) way which really isn't a great approach imo - it would have been better to be abstract.

That is, in a more ideal world, Finder would eventually be abstract and those methods protected - maybe there should be a AbstractFinder like that and Finder change to extend AbstractFinder.  People using DI in theory should be using BeanFinder or BeanRepository and not Finder (but the docs and javadoc don't explicitly push people that way).

**Comment by rbygrave** [comment]
Ok, I think we can close this topic off for now and see if more people ask for this syntactic sugar later on.
