### ISSUE TITLE
JSONB fields are not considered dirty after modified in BeanPersistController preUpdate

### ISSUE THREAD

**Issue by AntoineDuComptoirDesPharmacies** [ebean-orm/ebean#2710]
## Expected behavior

In `BeanPersistController` `preUpdate`, we updated a property of Jsonb field.
We expected that dirtyness of Jsonb field will be computed after this modification and `UPDATE` query would contains the modified Jsonb field.

## Actual behavior

"UPDATE" query does not include updated Jsonb field after modification in `BeanPersistController`.

### Steps to reproduce

```
@Entity
public class Ad {
    @ManyToOne(cascade = CascadeType.PERSIST)
    private AdStatus status;

    @DbJsonB
    @Column(nullable = false)
    private Ad.Journal journal;
    [...]
}
```

```
public class AdController implements BeanPersistController {
    [...]
    @Override
    public boolean isRegisterFor(Class<?> cls) {
        return cls.equals(Ad.class);
    }

    @Override
    public boolean preUpdate(BeanPersistRequest<?> request) {
        Ad ad = (Ad) request.getBean();

        Map<String, ValuePair> updatedValues = request.getUpdatedValues();

        if(!updatedValues.containsKey("status"))
            return true;

        ValuePair valuePair = updatedValues.get("status");

        if(!Objects.equals(valuePair.getNewValue(), valuePair.getOldValue()))
        {
            ad.getJournal().setStatusUpdatedAt(LocalDateTime.now());
        }

        return true;
    }
    [...]
}
```

**Comment by rPraml** [comment]
Can you try to set mutationdetection to HASH or SOURCE. See #2274
https://github.com/ebean-orm/ebean/pull/2274/files#diff-604753aa3c2cae1ad527322794be592f42ab26cb32e3b3e58bf9d3db5e1fa367

**Comment by AntoineDuComptoirDesPharmacies** [comment]
Thanks for your answer @rPraml,
Yes, we tried with mutationdetection `DEFAULT` (which is similar to HASH) `HASH` and `SOURCE`.
None of these mode triggered the addition of `journal` in "UPDATE" request.

The only workaround we found (which is a bit strange) was to re-call save on the object in the `BeanPersistController`.
For example : 
```
    @Override
    public boolean preUpdate(BeanPersistRequest<?> request) {
        Ad ad = (Ad) request.getBean();

        Map<String, ValuePair> updatedValues = request.getUpdatedValues();

        if(!updatedValues.containsKey("status"))
            return true;

        ValuePair valuePair = updatedValues.get("status");

        if(!Objects.equals(valuePair.getNewValue(), valuePair.getOldValue()))
        {
            ad.getJournal().setStatusUpdatedAt(LocalDateTime.now());
            request.database().save(ad, request.transaction()); // THIS IS THE NEW LINE TO FORCE DIFF CHECK ON JSONB
        }

        return true;
    }
```

I am wondering if diff check after BeanPersistController only use ref equality through `Objects.equals` instead of `HASH` / `SOURCE`.

**Comment by rbygrave** [comment]
This issue is all about `PersistRequestBean`.  Effectively the call `beanDescriptor.checkMutableProperties(intercept);` is happening too early for this case.

1. Change such that `beanDescriptor.checkMutableProperties(intercept);` executes after `controller.preUpdate(this)`
2. Move `updatedProperties = updatedProperties();` such that it occurs after the check on mutable properties
3. We also need to keep the `beanDescriptor.checkMutableProperties(intercept);` in the constructor for the cases where an updating bean is only dirty due to mutable properties

**Comment by rbygrave** [comment]
The current downside to the fix is that for the case where where we update a bean that isn't dirty (yet) ... and is only dirty via mutable properties (like DbJson etc) then the mutation detection runs twice. For DbJson properties those are converted to json twice (to check for dirty). 

More strictly, in the constructor (early) we only need to see if _something_ is dirty.
