### ISSUE TITLE
query.delete() will affect subsequent finds

### ISSUE THREAD

**Issue by rPraml** [ebean-orm/ebean#2720]
## Expected behavior
Having a `query = DB.find(SomeEntity.class).where()...query()` should produce same results on subsequent operations.

## Actual behavior

```java
query = DB.find(SomeEntity.class).where()...query()
query.findOne(); // will work
query.delete(); // will delete everything
//.. having some code here, that produces someEntity matching the query
query.findOne(); // will return a reference bean only with disabled lazy load
```

The issue here is in `query.delete()` - replacing by `query.copy().delete()` will solve the problem.

In my code, the query cannot be executed by statement, so we run in this code block:
```
        // escalate to fetch the ids of the beans to delete due
        // to cascading deletes or l2 caching etc
        List<Object> ids = request.findIds();
```
and this will call `query.setSelectId();` later

I remember, that `query.findIds()` makes an internal copy to avoid this problem

Do you think this is a bug or should mixing of different operations on a query be avoided?

cheers
Roland

**Comment by rbygrave** [comment]
Well, I have never _thought_ about doing `query.findOne()` `query.delete()` using the same query instance.

So my question is, can you provide more context / an example as to what the scenario is that means that we want to effectively (perhaps under the hood) do `query.copy().delete()` after a `findOne()`?

I presume the findOne() is approximately a unique key. We then choose to then do `query.delete()` rather than `database.delete(bean)` and I don't follow that part / I would like to understand better why `query.delete()` becomes the choice?

> Do you think this is a bug or should mixing of different operations on a query be avoided?

To some extent its:
- Mixing of different operations on a query isn't really _expected_ [by me] per say but ...
- What is the scenario where people may choose this option. If it makes good sense we should support it better -> bug. If it's low value and to be avoided then we ideally should try and prevent "miss use" some how -> bug.

I think the next step is to see if I can better understand the use case, better understand the thinking that lead to this use of `query.delete()` and using a single query instance to execute different options (well, probably its only about `query.delete()` executed after a `find*()`).

**Comment by rbygrave** [comment]
And the reason for doing `query.delete();` rather than `DB.delete(entity);` ?  Was there reasoning behind that?

**Comment by rbygrave** [comment]
Hi @rPraml  I'll close this for now with the view that we don't try and reuse a query like this.  You can reopen if you like.

Cheers, Rob.

**Comment by rbygrave** [comment]
Sweet.  We might still deal with it some day in the future ... but I think we should just see if this pops up again.
