### ISSUE TITLE
How to configuring the query-bean-generator

### ISSUE THREAD

**Issue by joelcho** [ebean-orm/ebean#2761]
I want to customize for generated query-bean and its `Association`, like:

- The prefix of query-bean name
- The access modifier
- The package where bean to save

---

As my purpose

```java
package org.example.domain;

@Entity
@Table(name = "table_name")
public class UserDomain extends io.ebean.Model {
    // properties....
}
```

The generated `Query Bean` should be

```java
package org.example.domain; // same package as domains

// internal / package  access only
/*public*/ class PrefixUserDomain extends TQRootBean<UserDomain, PrefixUserDomain> {
    // ....
} 
```

and `Association query bean` should be

```java
package org.example.domain; // same package as domains

// internal / package  access only
/*public */ class AssocPrefixUserDomain<R> extends TQAssocBean<UserDomain,R> {
    // ....
}
```

**Comment by rbygrave** [comment]
I don't think we can do this based on how the enhancement works for query beans.  You could try by manually copying and moving the generated code and see ... but I don't think it will work due to how query bean enhancement detects the actual query beans (as a .query subpackage of the entity bean package).

What is the motivation for this request?  What are you trying to achieve?
