### ISSUE TITLE
SoftDelete entities are hard deleted on orphan removal

### ISSUE THREAD

**Issue by Ichtil** [ebean-orm/ebean#2948]
## Expected behavior

Statefully replacing field that is ` @OneToOne(cascade = CascadeType.ALL, orphanRemoval = true)` should result in the old value having the soft delete column updated to true.

## Actual behavior

The old value is hard deleted (`delete from`)

### Steps to reproduce

Please see attached unit test. The unit test repository is running ebean version 13.6.5 (for newer versions there are some breaking changes), but this bug is happening in our application on the version 13.11.1.

**Comment by Ichtil** [comment]
https://github.com/ebean-orm/ebean/pull/2949

**Comment by Ichtil** [comment]
We have had some issues with soft delete before (https://github.com/ebean-orm/ebean/issues/2727 and https://github.com/ebean-orm/ebean/issues/2750), but they should be fixed in the version 13.6.5, so this looks like a different issue.

**Comment by Ichtil** [comment]
Ok, on second look, I had an old forked version of the repository, sorry for the confusion. But I still cannot get maven to import the project.  I'll have to look at later.

**Comment by Ichtil** [comment]
To clear up the confisuion - this bug happens on version 13.11.2, the current repo version of 13.11.3-SNAPSHOT couldn't be imported by maven. Could you please have a look at it?

**Comment by rbygrave** [comment]
So in version 11.22.9 Issue https://github.com/ebean-orm/ebean/issues/1505 added the code ...https://github.com/ebean-orm/ebean/commit/de9823b69bc7d053fb724a619b1e40b1315d5882#diff-b252eeaf218f406dfa45c3497ea358735b864214080d3ff07bccc72bd68f2cccR906

... and than **true** there means delete permanent.  Turning that to false is a normal delete that is changed to a soft delete if the entity in question has soft delete support.

That is, we have had this bug since 11.22.9 when that code was introduce rather than this being a regression.
