### ISSUE TITLE
@DbArray getter no longer initialised with empty list

### ISSUE THREAD

**Issue by simontankersley** [ebean-orm/ebean#3001]
## Expected behavior

Release notes noting that difference in behaviour from release 12 to release 13 where the following now returns null

```
@Entity
public class Pet {
    ...
    @Column
    @DbArray
    private List<String> list;
    ...
    public List<String> getList() {
        return list;
    }
    ...
```

```
    new Pet().getList() // this returns null in 13 but an empty list in 12
```

## Actual behavior

I didn't find this mentioned

### Steps to reproduce

```
git clone git@github.com:simontankersley/ebean-list-init-tests.git
ebean-list-init-12-test/gradlew -p ebean-list-init-12-test test
```

to 

```
git clone git@github.com:simontankersley/ebean-list-init-tests.git
ebean-list-init-13-test/gradlew -p ebean-list-init-13-test test
```

You'll see this code under 12 doesn't fail but does under 13

```
        assertNotNull(new Pet().getList());
```

**Comment by rbygrave** [comment]
Did you see https://github.com/ebean-orm/ebean/releases/tag/ebean-parent-13.12.0 ?

Alsi note that if the property/column is marked non-nullable then if will initialize as an empty list.

**Comment by simontankersley** [comment]
So sorry, missed it - thank you!

**Comment by rbygrave** [comment]
All good. 

For apps wanting the non-null behaviour the TLDR is to use `@DbArray(nullable=false)` or similar nullable false annotation.

... which tells ebean / ebean-agent that we do not want null. This means we will get automatic list initialisation and that means we can get an empty array but never a null array.

----
from https://github.com/ebean-orm/ebean/issues/2855

The fix is for the enhancement to take into account the nullable attribute via Ebean `@NotNull`, Kotlin `@NotNull`, `@Column(nullable=false)` and `@DbArray(nullable=false)`. For DbArray that are not null we will keep the automatic initialisation behaviour. For DbArray that are nullable we will not.
