### ISSUE TITLE
Transaction Locks not working all the time

### ISSUE THREAD

**Issue by fyrnaga** [ebean-orm/ebean#3043]
We have a situation in our application where the locks when in a serializable transaction does not always work.
We have a schedule job that updates an entity and a webhook call that we receive that can try to update the same entity.

To avoid this we added @Transactional(isolation = TxIsolation.SERIALIZABLE) to the method. When selecting the entity, we use the selectForUpdate option as well.

- Using ebean 13.8.0
- PaymentScheduleJob class is part of the org.example.manager.payment
- WebHookResource is part of the org.example.resource
- PaymentManager  is part of the org.example.manager.payment
- Thread 1 (t1) is running PaymentScheduleJob
- Thread 2 (t2) is listening fo call on WebHookResource

## Expected behavior

- If the t1 select first the payment, t2 should be blocked on the read
- If the t2 select first the payment, t1 should be blocked on the read

## Actual behavior

- If the t1 select first the payment, t2 is not blocked
- If the t2 select first the payment, t1 is blocked

### Steps to reproduce
- To reproduce we need to use debugger and break points to see the expected behaviour
- Was not yet able to produce a unit test scenario

``` ebean.mf
entity-packages: org.example.model
transactional-packages: org.example.manager
querybean-packages: org.example.manager
transient-internal-fields: true
check-null-many-fields: false
```

```java WebHookResource.java
package org.example.resource;

@Component
@Path("/webhook")
public class WebHookResource {

   @Autowired
   WebHookPaymentManager webHookPaymentManager;

   @POST
   @Path("/webhook/payment")
   public ApiResponse handlePayment(@Context HttpServletRequest request) {
...
webHookPaymentManager.handlePayment(payment);
...
   }

}
```

```java WebHookPaymentManager.java
package org.example.manager.payment;

@Component
@Path("/webhook")
public class WebHookPaymentManager {

   @Autowired
   private PaymentManager paymentManager;

   public void handlePayment(Payment payment {
      ...
      paymentManager.notifyPayment(payment, listEmails);
      ...
   }

}
```

```java PaymentScheduleJob.java
package org.example.manager.payment;

@Component
public class PaymentScheduleJob implements Job, InterruptableJob{

   @Autowired
   private PaymentManager paymentManager;

   @Override
   public void execute(JobExecutionContext context) {
      ...
      paymentManager.notifyPayment(payment, listEmails);
      ...
   }

}
```

```java PaymentManager.java
package org.example.manager.payment;

import io.ebean.annotation.Transactional;
import io.ebean.annotation.TxIsolation;
...
@Component
public class PaymentManager extends EbeanManager<Payment> {

   ...
   @Transactional(isolation = TxIsolation.SERIALIZABLE)
   public void notifyPayment(Payment payment, List<String> bccEmails) {
      payment = findForUpdate(payment.getId());
      // Doing Other stuff
   }
   ...
}
```

```java EbeanManager.java
package org.example.manager;
@Service
public abstract class EbeanManager<T> {
   protected Database ebeanServer;
   ...
   public T findForUpdate(UUID id) {
      T entity = ebeanServer.find(T).forUpdate().where().idEq(id);
      return entity;
   }
   ...
}
```

**Comment by fyrnaga** [comment]
Small questions on how ebean is handling transactions. Is it using instrumentation or is creating a wrapper around the java object?

**Comment by rbygrave** [comment]
> Is it using instrumentation 

Yes, it is using instrumentation. This means for example that we can put ebean `@Transactional` on private methods.

> unit test ...

Well, creating a unit test is absolutely the way to go especially with this type of case (2 threads, locking). I suggest what we typically need to do in the unit test is to slow things down (by milliseconds or seconds) to ensure we get the race/conflict/waiting that we expect.

That is, in my experience it is put the expected logic + transactions into the unit test and put in Thread.sleep() or LockSupport.park() to slow things down appropriately so that we actually observe the waiting/ordering that we expect with select for update etc.

What I expect to see is:
- The 2 transactions for the 2 different updates
- The actual code for both of these updates
- The specific database that is being used (Postgres, MySql etc with version)
- The test should use docker database containers, ebean-test, ebean-test-containers makes that easy
- The test really should be headless / not include http (unless its a component test but even then that suggests the issue has not been distilled into 'just the important parts')


Note that `TxIsolation.SERIALIZABLE` isn't necessary and changes things fairly dramatically. My suggestion would be to create the unit test that shows the 2 updates using the default READ_COMMITTED and then you should be able to see how that can work with SERIALIZABLE without the select for update (I can help show you that).

Note that at the moment the code above does not actually show us anything being updated and does not show us the 2 transactions. Also the `notifyPayment()` method looks odd taking a Payment instance only to replace it using select for update - that seems odd.

The recommendation for creating a test for this would be to fork https://github.com/ebean-orm-examples/example-minimal project. Modify the application-test.yaml platform to say Postgres at https://github.com/ebean-orm-examples/example-minimal/blob/master/src/test/resources/application-test.yaml#L5 ... and it will automatically use docker to run and setup docker Postgres database to run the tests.

**Comment by rbygrave** [comment]
Suggestions:
1. Turn on SQL and TXN logging

Turn on logging for `io.ebean.SQL` and `io.ebean.TXN` to ensure that the transactions are wrapping both the select for update and the actual update.

2. Remove from ebean.mf

It is no longer required for enhancement. If those packages specified are wrong then perhaps the `@Transactional` isn't being enhanced and if that occurred then there would be no transaction that wraps both the select for update and the actual update.

So I'd recommend removing the below lines from ebean.mf (or remove it altogether unless you need `transient-internal-fields: true` or `check-null-many-fields`)
```
entity-packages: org.example.model
transactional-packages: org.example.manager
querybean-packages: org.example.manager
```

**Comment by rbygrave** [comment]
> To reproduce we need to use debugger and break points ...

Just to say that debuggers stop all threads and for this sort of test imo we want the 2 threads running concurrently.  Hence I tend towards the "slow it down" approach by adding superficial sleep/park to get the ordering desired and to be able to observe the waiting in human observable milliseconds or seconds.

**Comment by rbygrave** [comment]
I'll close this for now.  Post back and update etc as needed.
