### ISSUE TITLE
[Feature] Exclude column from query

### ISSUE THREAD

**Issue by PromanSEW** [ebean-orm/ebean#3048]
I have `@MappedSuperclass` model and inheritors, which have field `user_id`.
I want to exclude this field from query, but I can't do this by `select`, as I have following method for query, and does not know about all fields:
```java
@Nonnull
public static <T extends InventoryItem> ExpressionList<T> byUser(Class<T> clazz, int user_id) {
	return DB.find(clazz).where().eq("user_id", user_id);
}
```
Where `InventoryItem` is `@MappedSuperclass`.
How to do this? I do not want to fetch `user_id` column for every row, as I know it already.
This field is simple `int` without `@OneToOne` and others:
```java
public int user_id;
```

**Comment by rob-bygrave** [comment]
> I want to exclude this field from query

I'm thinking that you mean exclude it from the "projection" / "select clause" ?


> but I can't do this by select, as I have following method for query, and does not know about all fields:

Just because a column is used in the where clause does not mean it can't be excluded from the select clause / projection.

We absolutely can choose to have a select that does not include columns that are part of the where. It is not clear to me why you think it can't be done?  Am I misunderstanding something?


> How to do this? I do not want to fetch user_id column for every row, as I know it already.

Specify a select() that does not include the user_id. That should just work.

**Comment by rob-bygrave** [comment]
Oh, unless you are looking for ... `@Basic(fetch = FetchType.LAZY)` ... which means **_by default_** do not include it in the projection.  That's probably what you are looking for / question makes more sense to me now if I read it that way.

**Comment by PromanSEW** [comment]
Thanks! `@Basic(fetch = FetchType.LAZY)` is that I am looking for!
