### ISSUE TITLE
Wrong initial value for DbArray on stateless update

### ISSUE THREAD

**Issue by AntoineDuComptoirDesPharmacies** [ebean-orm/ebean#3137]
## Expected behavior

On stateless update, DbArray with init value should be considered dirty and included in update query.

## Actual behavior

On stateless update, DbArray with init value is not included in update query.

### Steps to reproduce

```java
public class Test extends Model  {
  [...]
      @Id
      @GeneratedValue
      private Long id;
  
      private String name = null;
  
      @DbArray(nullable = false)
      @NotNull
      private List<String> values = new ArrayList<>();
  [...]
}

Test modifications = new Test ();
modifications.setId(32L);
modifications.update();

```

```console
10-07-2023 17:07:27.207 [http-nio-7078-exec-2] DEBUG io.ebean.SQL.performLog - txn[] update test set name=? where id=?; -- bind(null, 1)
```

Note : 
If i call `getValues()` before proceeding to update, the Array seems to receive its initial value and the SQL update query become correct.
So it seems that a workaround is to manually call DBArray properties `getters` before proceding to 'udpate'/'save' to be sure that initial value is loaded.

**Comment by rob-bygrave** [comment]
> On stateless update, DbArray with init value should be considered dirty and included in update query.

So No, I don't agree.

If Ebean did that then it would no longer be able to do a stateless update that _DIDN'T_ include the DbArray and we don't want that. 

My general expectation is that Java-wise we desire all our collections to be non-null - so that initialisation for the DbArray is expected [well, technically it doesn't matter in this `@DbArray(nullable = false)` case, Ebean will always init the DbArray just like it does for OneToMany and ManyToMany collections so as users we never deal with null collections].


If we want a stateless update to set an empty list for a `@DbArray` we should do that explicitly like:

```java
Test modifications = new Test ();
modifications.setId(32L);
modifications.setValues(new ArrayList());  // <- Setting an empty List
modifications.update();
```

If there is no setter method then we would have to consider doing:

`modifications.getValues(); // initialise the DbArray`
or perhaps `modifications.getValues().clear();`  


Does that make sense?

**Comment by AntoineDuComptoirDesPharmacies** [comment]
> Does that make sense?

There is two possible way of seeing @DbArray. Either it should behave as `OneToMany` and `ManyToMany` fields, or it should behave as a primitive field (`String`, `Integer`, ...).

On my opinion, as the values of @DbArray are not entities and as it is stored directly as a column value of the current entity, I was expecting it to behave more like primitive fields.

Following this point of view, it was strange having `String`, `Integer`, ... fields being initialized to their default associated value on DB stateless update and `DbArray` is not being touched.

So, as my initial expectation is wrong, I am wondering what what the arguments in favor of `DbArray` being processed the same as `OneToMany` and `ManyToMany` fields ?

Thanks in advance for your enlightments !

**Comment by rbygrave** [comment]
> it was strange having String, Integer, ... fields being initialized to their default associated value on DB stateless update

We could look at that closer. Specifically looking at the constructors being defined, Integer vs int etc and what is trying to be achieved. Do you want to share your example with that.

Ultimately,  stateless update is useful when the properties explicitly set are included in the update. My gut says that there is confusion when only 1 constructor exists and scalar types like String are initialized.  Put up an example and let's discuss it I reckon.

**Comment by AntoineDuComptoirDesPharmacies** [comment]
We can use a simple example derived from the topic example : 
```java
public class Test extends Model  {
  [...]
      @Id
      @GeneratedValue
      private Long id;
  
      private String name = null;
  
      // No constructor, only getters and setters
  [...]
}

Test modifications = new Test ();
modifications.setId(32L);
modifications.update();
```

In the past, we were surprised that on stateless update, `name` field is set `null` in the query but we were thinking that it is due to their default initialization, with Ebean considering the field dirty.

In the past few days, we were trying to exploit this "feature" in order to reset an entity to its default value in database.
For example, the code from the example would reset all columsn of entity '32' to their default values without the need to reset all fields by hand in code (via setters).

However, as `DbArray` are processed same as `OneToMany` and `ManyToMany` objects, only half of the entity is reset.

I am O.K with both behaviors, but It feels a bit strange that half of the entity is reset. I was expecting either all fields reset or none to get consistency in behavior.

Maybe the field should not be included when initialized with default value without using setters ?

**Comment by rob-bygrave** [comment]
> we were surprised that on stateless update, name field is set null in the query but we were thinking that it is due to their default initialization, with Ebean considering the field dirty.

Yes, but I'd suggest that is the choice of the developer per se (and not Ebean's choice).

> // No constructor

No **_explicit_** constructor meaning that a default constructor is created for us.  The important point is that there is now only the ONE default no-arg constructor and that constructor is shared for both when we want to insert and when we want to stateless update - one constructor is used for both cases.

So:
```java
public class Foo {

    private String name = null;

    // No EXPLICIT constructor, getters and setters
}
```
When we look at the Bytecode generated by Javac we see the default no-arg constructor and we see the name field being initialised to NULL in that default constructor via the `PUTFIELD`.

```
  private Ljava/lang/String; name

  public <init>()V
   L0
    LINENUMBER 3 L0
    ALOAD 0
    INVOKESPECIAL java/lang/Object.<init> ()V
   L1
    LINENUMBER 5 L1
    ALOAD 0
    ACONST_NULL
    PUTFIELD org/example/Foo.name : Ljava/lang/String;
    RETURN
   L2
    ...
```

Now, this example uses `private String name = null;` but it isn't clear what that ` = null` is actually here for - why is it not just `private String name;` instead?

The explicit initialisation of name to null is not something I would ever do and tbh I was not really expecting that. It actually puts extra Bytecode into the default constructor that generally is never useful? (because name would be null without it).

Having that extra Bytecode explicitly setting name to null in the default constructor is THEN something that ebean needs to deal with as you figured - _"due to their default initialization, with Ebean considering the field dirty"_ - that's right.  Plus for querying back a partially loaded bean that didn't include that initialised field ebean has to "unload" it / "deem it to not be loaded".   


> trying to exploit this "feature" in order to reset an entity to its default value in database

Hmm, that really doesn't sit well with me - I think you should be thinking that "explicit is better" wrt using stateless updates. 


> Maybe the field should not be included when initialized with default value without using setters ?

I don't know what this means.  I mean, why is there is ` = null` there? ... and note that there is only ONE constructor here so it must be shared for both insert and stateless update. Maybe I'm not seeing enough of the example with real world context to understand.


> as [non-nullable] DbArray are processed same as OneToMany and ManyToMany objects, only half of the entity is reset

These are all collections and hence we might not have _ANY_ setter (nor constructor param) at all. In that case they would only be mutated via add, remove, clear etc.  We can't do that with scalar types like String.  So yes, these collection types get more special treatment due to that (plus orphan removal plus optimisation for fetching partial objects).

Noting that a **_nullable_** `DbArray` actually doesn't get the automatic initialisation because in this case null is a valid and expected value for that nullable DbArray.

**Comment by AntoineDuComptoirDesPharmacies** [comment]
In fact you are right about `private String name = null;` being a bit weird but we have some historic code written this way.
Thank you for these insights, it is interesting to know how Bytecode is generated in this use case.
When we reproduce the same as bytecode manually, we indeed have the same behavior (need to call getter on list to produce value in stateless update).
```
public Foo() {
   this.name = null;
   this.myList = new ArrayList();
}
```

_Fun note_ : 
If you call `setMyList(new ArrayList())` instead of `this.myList = new ArrayList();`, the value is included in stateless update even if `getter` have not been called. Certainly due to the fact that interceptor is called and know that property have been modified.

To conclude and to be more safe against current behavior and possible future versions, we finally write an explicit `reset` method which is setting all fields to their default values and we explicitly call it when needed.

**Comment by rob-bygrave** [comment]
> To conclude  ... write an explicit _**reset method**_ which is setting all fields to their default values and we explicitly call it when needed.

I think this is really good. Nice and explicit intent that values are reset to defaults - I like it. Good result.


> `this.myList = new ArrayList();`

FYI: The _`PUTFIELD`_ on the persistent collection (OneToMany, ManyToMany, non-nullable DbArray) _[occurring in the default constructor]_ is detected by Ebean enhancement. Ebean will remove this Bytecode and then ensure that the collection is initialised on demand correctly (never null, orphan removal detection enabled if required etc).


> `setMyList(new ArrayList())`

FYI: Being a _method call_ and not a _`PUTFIELD`_ then that will not be detected by the ebean enhancement and not be removed etc. A workaround of sorts, to my eyes it seems too subtle though and FWIW I prefer the nice and explicit reset() method approach over this.

**Comment by rbygrave** [comment]
Ok, I think we can close this one.
