### ISSUE TITLE
Adding entity to @OneToMany property doesn't create the relationship

### ISSUE THREAD

**Issue by Incanus3** [ebean-orm/ebean#3142]
## Expected behavior

When I add entry to `@OneToMany` property or reset it to a new list containing the entry and save the referencing entity, I'd expect this new relationship to be persisted.

## Actual behavior

Neither the referencing entity's `@OneToMany` property, nor the referenced entity's `@ManyToOne` property reflects the new relationship after reload.

### Steps to reproduce

```java
// the entities

@Entity
public class Customer extends Model {
  @Id
  long id;

  String name;

  public Customer(String name) {
    this.name = name;
  }

  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Group getGroup() {
    return group;
  }

  public void setGroup(Group group) {
    this.group = group;
  }

  @ManyToOne(optional = true, cascade = {CascadeType.ALL})
  @JoinColumn(name = "group_id", nullable = true, insertable = true, updatable = true)
  private Group group = null;
}

@Entity
@Table(name = "groups")
public class Group extends Model {
  @Id
  long id;

  String name;

  public Group(String name) {
    this.name = name;
  }

  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public List<Customer> getMembers() {
    return members;
  }

  public void setMembers(List<Customer> members) {
    this.members = members;
  }

  public void addMember(Customer member) {
    this.members.add(member);
  }

  @OneToMany(mappedBy = "group", cascade = {CascadeType.ALL})
  private List<Customer> members = new ArrayList<>();
}

// the test

@Test
void add_from_one_to_many_side() {
  Database server = DB.getDefault();

  Customer rob = new Customer("Rob");
  server.save(rob);

  Group devs = new Group("Devs");
  server.save(devs);

  devs.addMember(rob);
  server.save(devs);

  Customer reloadedRob = server.find(Customer.class, rob.getId());
  Group reloadedDevs = server.find(Group.class, devs.getId());

  // THESE FAIL
  assertThat(reloadedRob.getGroup()).isEqualTo(devs);
  assertThat(reloadedDevs.getMembers()).isEqualTo(List.of(rob));
}
```

```console
Expected :Group@0(id:1, name:Devs, members:[Customer@1(id:1, name:Rob)])
Actual   :null
Expected: [Customer@0(id:1, name:Rob)]
 but was: []
```

* I've created a repository reproducing this problem [here](https://github.com/Incanus3/one-to-many-writes-test), the failing test is [here](https://github.com/Incanus3/one-to-many-writes-test/blob/master/src/test/java/org/example/domain/CustomerTest.java#L97)
* after reading through [this issue](https://github.com/ebean-orm/ebean/issues/547) we added the second test that adds the member into the `BeanList` instead of replacing the whole list, but it doesn't solve the issue
* we've traced through most of `server.save(devs)` call and the save correctly cascades to the `DefaultPersister.saveAssocMany()` method where the `members` property is processed and `saveRecurse()` is called with `rob`, but when the `Customer.group` property is processed [here](https://github.com/ebean-orm/ebean/blob/master/ebean-core/src/main/java/io/ebeaninternal/server/persist/DefaultPersister.java#L1060), the `prop.valueAsEntityBean(request.entityBean())` call returns `null`, which means the reversed property's value is never set.

**Comment by Incanus3** [comment]
From reading through the [mentioned issue](https://github.com/ebean-orm/ebean/issues/547) I understand that removing items from the `@OneToMany` side is a use-case that's not supported intentionally, does the same hold for adding to the list?

**Comment by rbygrave** [comment]
@jnehlmeier Is right but there is something subtle that I can explain and in that sense explain how this could be considered a bug.

With OneToMany with a cascade=PERSIST | ALL ... Ebean _WILL automatically_ set the bi-directional relationship (so I this case set the Group on the Customer) **_IF_** the beans being cascaded to [Customer in this case] is in a **_NEW_** state or **_DIRTY_** state.

That is, it is not working as you had expected here because the Customer bean instance is in LOADED state and not DIRTY.

----
What you might have desired would be [when the cascaded bean is in loaded state and not dirty] for ebean to then check the relationship property, check the Group on the Customer instance and if that Group on the Customer was either NULL or different [by id value] to the cascading Group instance ... then automatically set that Group.  

That would make the Group property dirty on Customer and we'd see a `update customer set group_id = ? where id = ?`

----
So maybe this is a bug in that sense. Hmm.

**Comment by rbygrave** [comment]
Ok, quite a lot here - I'm not sure I'll cover it all.  Firstly we need some "big picture" about when cascading a OneToMany is appropriate I think.

### "Ownership" type relationship vs "Assignment" type relationship

For myself I look to classify OneToMany relationships as "Ownership" or "Assignment".  TLDR Ownership type relationships are appropriate for cascading (and orphan removal).

"Ownership" type relationships can be identified by asking a few questions. Taking Orders and Order Lines as a classic example:

- Q: Can Order lines be created without an Order? **_No._**
- Q: If an Order is deleted, must the related Order lines also be deleted? **_Yes_**
- Q: Can an Order Line be "re-assigned" or "moved" to a different Order?  **_No_**

There is a strong "Ownership" relationship - An Order Line is "owned" by its associated Order.


For "Assignment" type relationships we ask the same questions and get different answers. For the purpose of explaining this I'm going to use Customer and Group from above and I'll make up the answers.

- Q: Can Customer be created without a Group?  **_Yes_** 
- Q: If a Group is deleted, must the related Customers also be deleted?  **_No_**, we instead "unassign" those Customers by setting their group to null.
- Q: Can a Customer be "re-assigned" or "moved" to a different Group? **_Yes_**.


### In-Memory modify and Flush 

With JPA, the approach in general terms is to modify the in-memory model (modify beans, add/remove them from collections etc) and the Flush the entire model to the database. This tends to encourage developers to think above adding/removing beans from collections and using cascade persist ... even for "Assignment type" relationships ... and even when this is a relatively bad idea.

The problem with the "add/remove from collection and flush/cascade" type approach is that it requires the collection to be loaded into memory. If the collection is large this can really hurt but it can actually be inefficient  if the only thing we are doing is "assignment" or "unassignment" [set the foreign key value]. For example, this can be done with a "stateless update" / single sql update statement and without loading any beans or collections into memory.

If we are cascade persisting from Group to its associated Customers in order to unassigned a customer from the group that is a really inefficient way to do it compared to:
```java
customer.setGroup(null);
customer.save();
```

> `@PrivateOwned`

PrivateOwned was the old feature that became  JPA "Orphan Removal" which is an attribute of `@OneToMany` like `@OneToMany(cascade = ALL, orphanRemoval = true)`.

Orphan removal **_should_** imo go along with `cascade = PERSIST` or `cascade = ALL`. Orphan removal also should **_ONLY_** be used with a "Ownership" type of relationship. 



> why should it set the reversed (mappedBy) property in some states but not in others?

I'd say because this is an "unassignment".  It is the case of using `cascade=PERSIST` on a "Assignment" type relationship where removing from the collection is expected to mean "unassignment" [set the foreign key to null]. This is what you are expecting but in general:
- JPA folks will tend to follow Jen's approach
- Ebean orientated folks are not use cascade on the collection for this because it tends to be inefficient and requires the entire collection to be held in memory.

This is maybe why we don't have many people asking about this.


> lots of other ebean users that will hit a similar problem.

If they are they are being pretty quite about it.



I think the main point is to see if you can see "Ownership" vs "Assignment" type relationships and maybe see why I think its a bad idea to lean on cascade PERSIST for "Assignment" type relationships.  

For example, if a Group can have thousands of Customers in its collection then it's pretty obvious adding/removing from the Group customers collection is getting expensive and doing "assignment" / "unassignment" via that approach is not good.

**Comment by Incanus3** [comment]
Hi guys, I'm sorry for the long delay in responding, I was away for a few weeks and then I completely forgot about this.

As for @rbygrave's response, everything you say makes perfect sense to me, when viewed with the mindset you describe, especially when talking about "assignment" type relationship, although I'm a bit surprised there aren't more people struggling with this. Maybe people just understand this distinction without having to be told like me :).

But, if I were sure my specific relationship (not the customer-group one I've used in the example, I've only used that for the sake of familiarity, our domain in this case is actually document-subdocuments, which is basically the order-items type), and if I didn't mind the inefficiency of having to load the whole collection into memory, am I to understand that if I annotate it with `@OneToMany(cascade = ALL, orphanRemoval = true)`, it should work as I expected? Because I think I tried that and the save didn't cascade on the removal either.

Thank you again for your patience with me.
