### ISSUE TITLE
@Id should use bigserial on Postgres

### ISSUE THREAD

**Issue by macruch** [ebean-orm/ebean#3291]
## Expected behavior
When I use
```java
@Id
private Long id;
```
the type in the generated sql should be bigserial
## Actual behavior
the type in the generated sql is bigint
### Steps to reproduce
Having a fully set up project with entities and create the schema/sql with this:
```java
DefaultDbMigration dbMigration = new DefaultDbMigration();
dbMigration.setPlatform(Platform.POSTGRES);
dbMigration.setApplyPrefix("V");

dbMigration.setStrictMode(false);
dbMigration.generateMigration();
dbMigration.generateInitMigration();
```

## Why is this important
currently bigint is used, the PK contraint is set and the sequence is created explicitly.

With bigserial only the PK contraint is needed. The sequence is created implizit by postgres, as well that the sequence is used as a default value for the PK

The difference is important when you add manually data: you have to define the PK in your statement, the sequence does not recognize this and when ebean want's to add an entry it might choose an value which was already used.

When the sequence would be used as a default value I could leave the PK value empty and the database would create it for me in my custom scripts, but I was not able to annotate the id so that ebean would generate this. As said: with bigserial/serial postgres would do this anyway.

### Workaround
```java
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Identity(generated = IdentityGenerated.ALWAYS)
    private Long id;
```
With this solution I get no duplicates between ebean and custom init scripts. Moreover it disallow to assign your own pk value on inserts. 
Disadvantage: for every insert the next pk value needs to be retrieved by checking already used values. With sequence ebean could get a batch of new values. 

Would be great to have bigserial as default or at least some configuration parameter an this.

**Comment by jnehlmeier** [comment]
`Platform.POSTGRES` tells ebean to use Postgres 10+ defaults and if I remember correctly it will then choose to use PostgreSQL `IDENTITY` column definition instead of `serial / bigserial`. Using `IDENTITY` is preferred as it fixes some surprising behavior and inconveniences compared to `serial / bigserial`. So in that case it seems logical that `bigint` is used.

The sql should look similar to
```
create table mytable (id bigint primary key generated by default as identity);
```

If you use `Platform.POSTGRES9` it will probably use `serial / bigserial`.

**Comment by rob-bygrave** [comment]
> bigserial

IDENTITY is preferred over BIGSERIAL etc with better features and being more standard.

> `generated always as identity`

Ebean by default with use `generated by default as identity` - so you'd expect to see **by default** and not **always** in the DDL there.  It isn't clear why you are seeing `always` but that is not expected. 

> you to provide a pk value for manual inserts (test data or initial data, etc) and brings the risk of already used pk values

I believe you are looking to use the `START WITH` option.  JPA standard annotations do not support this so we need to use the ebean specific `@Identity` annotation - https://ebean.io/docs/mapping/extensions/identity

For example:

```java
@Identity(generated = BY_DEFAULT, start = 1000, cache = 100)
@Entity
public class AuditLog {
  @Id
  private Long id;
```

```sql
create table audit_log (
  id                            bigint generated by default as identity (start with 1000 cache 100) not null,
  description                   varchar(255),
  modified_description          varchar(255),
  constraint pk_audit_log primary key (id)
);
``` 

Then all tests can supply Id values less than the starting value [of 1000 in the example above]. 

> like DEFAULT nextval('products_product_no_seq')

So although this works it is a bad approach when we really want to scale "lots of inserts". The reason behind that is that whenever a `nextval` is executed there is a light weight lock being used (in Oracle RDBS speak a "latch"). If we have a log of concurrent inserts this results in contention. It is this potential contention that we want to minimise. [This latch is an in-memory lock and not transactional etc so its "light weight" but it isn't "free / zero cost"]

This is why JPA `@Sequence` has a default `allocationSize` of **50** (which translates to the sequence step size) [and this matches the Oracle RDBMS view of how applications are _expected_ to use sequences in order to reduce the contention on the sequences latch - that AND use the **cache** option for identity and sequence which both Oracle and Postgres support etc].

That is, with `@Sequence` the default is that we have `allocationSize=50`.  The ORM is expected to obtain the nextval (say 50) and then can use that value plus the next 49 values [50,51,52,53 ... 99] _without_ going back to the database and without using the associated latch [1 latch use per 50 rows inserted which is less contention compared to 1 latch use per 1 row inserted].

In this way any sort of `default nextval` would be ok for all small tables with not many inserts but generally undesirable for any tables where we expect a lot of inserts to occur.

**Comment by macruch** [comment]
Thanks for the explanation regarding bigserial and DEFAULT nextval.

> Ebean by default with use generated by default as identity - so you'd expect to see by default and not always in the DDL there. It isn't clear why you are seeing always but that is not expected.
This is because I use `@Identity(generated = IdentityGenerated.ALWAYS)` . With this no primary keys values are allowed during insert and so I prevent potential collisions.

Relations in testdata are resolved like this: 
`insert into .... (person_id. ...) values ( (select id from person where name = 'test user'), ...);`
it's a bit more effort in writing it, but makes it also more robust.

But thanks for the tip with the start value. I will see if this suits better at some time in the project.
