### ISSUE TITLE
missing platform for hsqldb

### ISSUE THREAD

**Issue by tbee** [ebean-orm/ebean#3518]
With EB13 platforms were introduced. Are there any plans for supporting HSQLDB?

**Comment by rbygrave** [comment]
By supporting do you mean having a "composite" like `ebean-h2`, `ebean-postgres` etc? 

I am wondering why you are using hsqldb rather than h2. I'm curious what would be the reason there. Plus are you looking to use hsqldb for testing only or is this a production use case? What is the background for this question because honestly I just use h2 myself and didn't think hsqldb was as good [but I've lost touch as well as I tend to always use ebean-test-containers these days and rarely use h2 for testing].

**Comment by tbee** [comment]
I mean EB can specify a platform (https://ebean.io/docs/database/), and hsqldb is missing. 

Interesting question you ask, which basically I describe here https://www.tbee.org/2024/03/30/simple-problems-simple-solutions-great-joy/. So I use the database is production for small projects. I'm not sure what made me pick hsqldb over h2, but hsqldb has not let me down in any way, so I see no reason to switch. It's easy, performs well enough, handles lobs with compression, my latest thing was with it not supporting "group by 1,2,3" (column index instead of repeating the select expression), but they support column alias, which may even be better than indexes.

**Comment by rbygrave** [comment]
> and hsqldb is missing.

So you mean it's missing from the **_documentation_** ... because `io.ebean.annotation.Platform.HSQLDB` exists. I'm probably missing the point here - is this just about missing documentation or something else?

> hsqldb over h2

FWIW: They both were originally authored by Thomas, that is h2 was written by the same author of hsqldb as a _rewrite_ (refer http://www.h2database.com/html/history.html). This is why for myself I'd prefer h2 over hsqldb [because it's the 2nd iteration from the same author].

**Comment by tbee** [comment]
Ow. Then it is about me first looking at the documentation instead of trying the code completion.

But interesting. It makes sense to prefer H2 probably, although HSQLDB is still maintained. Thanks for the insight.
