### ISSUE TITLE
Q: generating rename migrations

### ISSUE THREAD

**Issue by Incanus3** [ebean-orm/ebean#3524]
Hi guys,
a few weeks back we started using ebean-migration and encountered a few issues. For issues I'd classify as bugs, I've created issues in the ebean-orm/ebean-migration repository [here](https://github.com/ebean-orm/ebean-migration/issues/161) and [here](https://github.com/ebean-orm/ebean-migration/issues/162) and for a question about how to generate a rename migration, I've created a discussion [here](https://github.com/ebean-orm/ebean/discussions/3521), but none of these has received any attention. Could you please have a look at those?
Thank you and best regards.

**Comment by rbygrave** [comment]
Ok, I think we can probably close this one now. People can refer to the linked discussion for the details ... 

**_TLDR_** Table rename and Column rename migrations are _intentionally_ not automatically generated because they are "breaking changes". For these cases we need to do them manually [create the migration xml and sql manually] and understand we need an outage to roll out those migration changes.
