### ISSUE TITLE
Deprecate TransactionEventListener ... migrate to TransactionCallback

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/ebean#807]
TransactionCallback has pre/post commit and rollback and you register with each transaction you are interested in.  Much better than TransactionEventListener ... so please migrate to that.

**Comment by shanness** [comment]
Hi @rbygrave, we are in the middle of a play upgrade (from 2.4 to 2.6) mainly to get up to a more modern version of ebean. We use the TransactionEventListener to tell ebean to run some critical code on each postCommit or postRollback, and register it as such :- 
        serverConfig.getExternalTransactionManager().add(listener);

I'm a bit confused about how to replace this with something that I have register every transaction (instead of just once at ebean startup).  Any help would be appreciated.

Thanks
