### ISSUE TITLE
Ebean not fetching complete list of attribute beans when equals(Object o) is implemented

### ISSUE THREAD

**Issue by archie-sh** [ebean-orm/ebean#879]
Google groups discussion https://groups.google.com/forum/#!msg/ebean/pI2hkuSTWdw/oaBC2HYiBAAJ

Failing test code example 
https://github.com/archie-sh/example-minimal

**Comment by rbygrave** [comment]
The issue here is that the equals implementation is interesting (implementing equals/hashCode is very hard to do on entity beans that by nature mutate).  The bug being that when loading a ToMany via lazy loading Ebean internally checks if the bean is already contained in the list (which can be the case in some cases).

The bug in this scenario is that BeanList uses list.contains() for this check and that in turn uses the .equals() method.  In the given test case the equals() implementation means that the second bean (different instance but equals() true) is excluded from the list - hence the failing test case (expects 2 but got 1).

The fix is for BeanList to internally use instance equality instead.

Rob note: The test in com.avaje.tests.model.survey.TestOrderByFetch shows why this check exists in the first place.
