### ISSUE TITLE
"develop" branch and SNAPSHOT release

### ISSUE THREAD

**Issue by 0xbaadf00d** [ebean-orm/ebean#905]
Hi @rbygrave,

Is it possible to create a branch "develop" and configure TravisCI to publish on Maven (eg : SonaType or other) with `-SNAPSHOT` after each build completed with success on "develop" branch ?

It allow users to have last version without waiting for official stable releases.

**Comment by rbygrave** [comment]
Maybe.  It is not a top priority as I see it though and unless there is demand stated on the google group it likely won't be done.

Usually we release pretty frequently. This current 9.3.1 release has dragged a bit but otherwise we have been pretty good at releasing frequently.

I should state that I do expect and desire that these types of discussions occur on the Ebean google group. My desire is that github issues map to a commit and that people registered as "watchers" get a high quality feed (without lots of back and forth discussion).

This policy is stated at: http://ebean-orm.github.io/support

Cheers, Rob.
